### ISSUE TITLE
Fake D** pi0pi0 component in D** heavy MC

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#121]
Due to a bug in the $D^{\*\*}$ heavy `.dec` file, no $D^{\*\*} \pi^0 \pi^0$ event is generated. According to the Clebsch-Gordon table, the $\pi^0 \pi^0$ vs. $\pi^+ \pi^-$ should be about 1/2.

We can _fake_ the $\pi^0 \pi^0$ component by randomly selecting 1/3 of $\pi^+ \pi^-$, and set its isolation BDT score to 0 (i.e. isolated).

This is a bug spotted by @CoffeeIntoScience when looking at step-3 fit log.

@afernez I'm looking at our truth-matching nomenclature again: https://umd-lhcb.github.io/lhcb-ntuples-gen/technical_concepts/truth_matching/

It seems that we don't differentiate between $\pi^0 \pi^0$ and $\pi^+ \pi^-$ right? This is not a problem, as RD+'s tuple tool extract truth info up to B grand-daughter, and the dec file (`12675010`) seems to have NO cascade $\pi \pi$ decay so looking at a heavy $D^{\*\*}$ should be sufficient (as Phoebe pointed out):

```
Decay B-sig 

  0.05  MyD*(2S)0      mu-  anti-nu_mu         PHOTOS  ISGW2;
  0.45  MyD(2S)0       mu-  anti-nu_mu         PHOTOS  ISGW2;
  0.45  MyD(2750)0     mu-  anti-nu_mu         PHOTOS  ISGW2;
  0.05  MyD(3000)0     mu-  anti-nu_mu         PHOTOS  ISGW2;

 
Enddecay
CDecay B+sig

Decay MyD*(2S)0 
0.08     MyD0 pi+ pi-                     PHOTOS PHSP;
Enddecay
CDecay MyAntiD*(2S)0

Decay MyD(2S)0 
0.08     MyD0 pi+ pi-                     PHOTOS PHSP;
Enddecay
CDecay MyAntiD(2S)0

Decay MyD(2750)0 
0.08     MyD0 pi+ pi-                     PHOTOS PHSP;
Enddecay
CDecay MyAntiD(2750)0

Decay MyD(3000)0 
0.08     MyD0 pi+ pi-                     PHOTOS PHSP;
Enddecay
CDecay MyAntiD(3000)0

Decay MyD0
  1.00   K-  pi+                           PHOTOS PHSP;
Enddecay
CDecay MyAntiD0
```

**Comment by yipengsun** [comment]
I think I can get away by just checking the third digit from Alex's truthmatching code.

**Comment by yipengsun** [comment]
I used the correct truth-matching code, and it looks like it's working:
![iso_bdt](https://user-images.githubusercontent.com/33738176/194732783-2969697b-d0be-4937-821b-120aed2304b6.png)
![iso_bdt_diff](https://user-images.githubusercontent.com/33738176/194732784-e4141a64-aff7-4c0f-8506-e8f39533a5ee.png)
![iso_bdt_raw](https://user-images.githubusercontent.com/33738176/194732785-aed25c7f-c4a2-4d08-9a5c-f7e7841bb872.png)

**Comment by yipengsun** [comment]
@afernez I think the truth-matching document needs updating/clarification: https://umd-lhcb.github.io/lhcb-ntuples-gen/technical_concepts/truth_matching/

I was led to believe that $D^{\*\*}$ heavy should have a truth-matching code of `400`, instead of `400400` (even though the example below listed the correct value). Can you update on why `b1b2` can be non-0?

**Comment by yipengsun** [comment]
Oh I see, I was wrong. You stated that for $D^{\*\*}$ heavy, the left-most digit would be either `3` or `4`. My bad.

**Comment by yipengsun** [comment]
Looking at some updated $D^{\*\*}$ heavy templates:

![d0_dsthmudst](https://user-images.githubusercontent.com/33738176/194755718-2a2cb4ac-aae7-4217-857b-ce51791871cf.png)

The ISO changed shape (due to addition of fake $D^{\*\*} (\text{heavy} \pi^0 \pi^0$, but the rest 3 do not change much.

I think this makes sense, as we randomly (uniformly) select 1/3 of total sample to fake, so there should be about 1/3 of samples in each skim that got chosen.

**Comment by yipengsun** [comment]
Not all $D^{\*\*}$ heavy are $\pi^+ \pi^-$. Some of them are $\pi^+ \pi^0$. So I need to make sure the $\pi^+ \pi^0$ are not affect by this faking procedure.

**Comment by yipengsun** [comment]
Previously, in the control fit:
```
103: fpipiratio1OS			 = 1.11625 +/- 0.56278
104: fpipiratio2OS			 = 0.182803 +/- 0.0803794
105: fpipiratioDD			 = 1.65124 +/- 0.47471
106: fppipiratio1OS			 = 0.000100246 +/- 0.0915764
107: fppipiratio2OS			 = 0.000100001 +/- 0.0337221
108: fppipiratioDD			 = 0.400168 +/- 0.24407
109: fzpipiratio1OS			 = 0.688618 +/- 0.624178
110: fzpipiratio2OS			 = 0.626734 +/- 0.0761429
111: fzpipiratioDD			 = 0.88695 +/- 0.390446
```

Now: 
```
103: fpipiratio1OS			 = 0.733319 +/- 0.362797
104: fpipiratio2OS			 = 0.187967 +/- 0.0687233
105: fpipiratioDD			 = 1.48643 +/- 0.372764
106: fppipiratio1OS			 = 0.0145499 +/- 0.411652
107: fppipiratio2OS			 = 0.0001 +/- 0.0560909
108: fppipiratioDD			 = 1.06207 +/- 0.274902
109: fzpipiratio1OS			 = 1.93883 +/- 0.275578
110: fzpipiratio2OS			 = 0.805841 +/- 0.0657347
111: fzpipiratioDD			 = 0.737627 +/- 0.345952
```

It's not significantly better.

**Comment by yipengsun** [comment]
The histogram comparisons: 
[comp_no_pi0pi0_fix.pdf](https://github.com/umd-lhcb/lhcb-ntuples-gen/files/9867963/comp_no_pi0pi0_fix.pdf)

**Comment by yipengsun** [comment]
Phoebe will do a similar comparison on her templates w/ and w/o `pi0pi0` fix to see if the effects are similar to us.

**Comment by yipengsun** [comment]
Tried to allow `fzpipi, fppipi` go negative. Doesn't work for step-3 signal fit: https://github.com/umd-lhcb/rdx-run2-analysis/issues/80#issuecomment-1295992823

**Comment by yipengsun** [comment]
Just checked again: Running the `pi0pi0` faking procedure on 2 MC:

## `12675011`

```
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, but don't change isolation.
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
Found a heavy D**: Event pi+pi- only, set to isolated
```

## `11674401`

```
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
Found a heavy D**: Event contains a pi0, skipping...
```

**Comment by yipengsun** [comment]
@afernez For now it's on Alex's plate.

**Comment by afernez** [comment]
Nevermind... got them.

**Comment by afernez** [comment]
Here [comp_no_pi0pi0_fix_run1.pdf](https://github.com/umd-lhcb/lhcb-ntuples-gen/files/10062367/comp.pdf) are the comparison histograms for run1 (Phoebe's $D^{\*\*}\_{H}$ templates with and without faked $\pi^+ \pi^- \rightarrow \pi^0 \pi^0$ fix), generated using `histos-noHeavyDstst2Xpi0pi0` and `histos-withHeavyDstst2Xpi0pi0faked` from [this shared CERNBox folder](cernbox.cern.ch/files/spaces/eos/user/b/bhamilto/Proctuples).

In general, the run1 and run2 (plots in file linked to in Yipeng's comment above in issue) show similar trends:
  - the majority of the differences with/without $\pi^0 \pi^0$ fix are in the iso sample, with the control samples mostly unaffected
  - run1 and run2 changes all seem to be in the same direction, ie. $m\_{\text{miss}}, E\_{\mu}^{\*}, q^2$ all move in the same direction when going from with to without the $\pi^0 \pi^0$ fix
  - in general, the differences between with/without the $\pi^0 \pi^0$ fix are _smaller for run1_, though only slightly, and there are a handful of exceptions

**Comment by yipengsun** [comment]
Good job! I think at this point we can say that our $\pi^0\pi^0$ fix is probably bug-free.

**Comment by yipengsun** [comment]
Reported in GM and consider this done.
