### ISSUE TITLE
Missing D^0 DDX decays

### ISSUE THREAD

**Issue by afernez** [umd-lhcb/lhcb-ntuples-gen#125]
Phoebe reminded us that for run1, some $DDX$ decays were missing in the cocktails for the $D^0$ sample--in their ANA, they noted the decays were "of the general topology $B\rightarrow D^{\*}[\rightarrow DzX]DK^{\*}$" (without a $\tau$). Checking the dec files (run2--identical to run1--[11894600](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/v32r6/dkfiles/Bd_D0DX,muX=cocktail,RDstar,TightCut.dec) and [12893600](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/v32r8/dkfiles/Bu_D0DX,muX=cocktail,RDstar,TightCut.dec) for $D^0$, [11894610](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/v32r6/dkfiles/Bd_Dst+DX,muX=cocktail,RDstar,TightCut.dec) and [12895400](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/v32r8/dkfiles/Bu_Dst+DX,muX=cocktail,RDstar,TightCut.dec) for $D^{\*}$), the problem seems to be that for some decays where one $D$ ends up as $K\pi (\pi_{slow}/\gamma)$ and the other $D$ yields the $\mu$, the interchanged decay where the former $D$ yields the $\mu$ and the latter $D$ the $K\pi (\pi_{slow}/\gamma)$ isn't included in the cocktail, but if the two $D$ mesons aren't the same (eg. not just $D^{\*+}D^{\*-}$) and both could potentially give the $\mu$ or $K\pi (\pi_{slow}/\gamma)$, the interchanged decay isn't identical and should be added to the cocktail.

_Note_: in the dec files, the $D$ mesons that could give either a $\mu$ or $K\pi (\pi_{slow}/\gamma)$ are $D=D^{\*+},D^{\*0},D^0$, and the naming convention is such that a particle whose name includes "Other" will give a $\mu$ while the non-"Other" will yield $K\pi (\pi_{slow}/\gamma)$.

Phoebe suggested we could potentially follow the same path as run1 and account for these missing decays by re-using comparable events from the $D^{\*}$ sample. To implement this, I started writing a script in this repo that would manually add on the $D^{\*}$ sample events (reconstructed as $D^0$--it's very nice that we had already reconstructed every event in both the $D^0$ and $D^{\*}$ modes!) to the postprocessed $D^0$ sample muonic $DDX$ ntuples--postprocessing the events following the same workflow as normal $DDX$, but adding on some truth-matching code to select out the specific missing decays and also fake-passing the $D^{\*}$ veto for half of the events (I'm not sure I understand this still... the run1 ANA notes that this is done "to mimic the $D^{\*0}$ component which would otherwise still be missing in this approach"). However, I quickly found that the added truth-matching was cutting everything out, and it doesn't seem to be an accident.

The specific decays in the $D^0$ $DDX$ dec files that seem to be missing are

- `MyOtherD*- MyD0 K*+`
- `MyOtherD*- MyD*0 K*+`
- `MyOtherD*- MyD0 K+` (not a $K^{\*}$, but I don't see why this decay shouldn't be included too?)

but... these decays are also missing in the $D^{\*}$ $DDX$ dec files!

Unless I'm fundamentally misunderstanding what the issue is and what run1 did, I don't think we can get events for these decays without requesting additional MC.

@yipengsun (just because I had said I would check my plan to implement this with you)

**Comment by yipengsun** [comment]
Naively, I think by "reusing", we just need to manually set the `d0_dst_veto_deltam` to a large value (e.g. `100`) so that
`d0_dst_veto_ok` is `true` (this means that the event is **unlikely** to be a `D*` event). In addition, in the truth-matching for the corresponding `D0` decays, we now accept `D*` event as well.

Is my understanding above correct?

However, the main problem seems to be that the `D*` decays (`MyOtherD*- MyD*0 K*+`) are missing as well...

**Comment by hadjichris** [comment]
@afernez Thanks Alex for this summary. Give me a few more days to digest the material so that I can verify what you are proposing and we can talk early next week. I will also contact Scott to get more information about the $\Lambda_b^0$ background. Eventually, we might want to include that in our MC request.

**Comment by afernez** [comment]
In our analysis meetings I guess we've agreed to make a new .dec file with just the missing decays, and we'll make a MC request with that. To put together/finalize what we've discussed for stats/BFs: I think we can use the same relative ratios as for the analogous decays, ie.
```
Decay B0sig (old)                  -->          Decay B0sig (new)
0.0020 MyD*- MyOtherD0 K+          -->          0.0020 MyOtherD*- MyD0 K+  
0.0018 MyD*- MyOtherD0 K*+         -->          0.0018 MyOtherD*- MyD0 K*+
0.0033 MyD*- MyOtherD*0 K*+        -->          0.0033 MyOtherD*- MyD*0 K*+  
```
and then for overall stats multiply by 1.5 to account for the fact that `MyOtherD*-` can decay as $D^0 \pi^-$ (isospin argument->2/3; this is the only decay mode for `MyD*-`) or as $D^- \pi^0(/\gamma)$ (isospin argument->1/3). This is similar to what was done in the 11894600 dec file for `MyD*- MyOtherD*0 K+` (BF=0.0079) vs `MyOtherD*- MyD*0 K+` (BF=0.0118). Overall, this will mean 1.5\*0.066\*547.4M=**54.1M** simulated events (the 0.066 comes from the sum of these decays relative BFs over the sum of all the `B0sig` BFs in the 11894600 dec file). Broken down by year (referencing [table](https://github.com/umd-lhcb/group-talks/blob/b4289e11af7a7dc16996fd1051d22a155b54f6e9/rdx/tables/Run2_MC_request_splitbyyear.pdf)):

| Decay | Nsim [M] 2015 | Nsim [M] 2016 | Nsim [M] 2017 | Nsim [M] 2018 | Nsim [M] | % Prev Tot Req |
| --- |:---:|:---:|:---:|:---:|:---:|:---:|
| B0->D0(Xc->munuX')X (delta) | 2.65 | 15.26 | 15.91 | 20.29 | 54.10 | 0.7% |

**Comment by afernez** [comment]
We've requested the missing DDX MC, it's been produced, and we've integrated it into our tuples, so I'll close this.
