### ISSUE TITLE
Reconstruct ReDecay D* Inclusive MC

### ISSUE THREAD

**Issue by afernez** [umd-lhcb/lhcb-ntuples-gen#128]
I've been trying to modify our [Davinci reconstruction script](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/d04e9b247cd87c5e265b068bf378fbcdadab3101/run2-rdx/reco_Dst_D0.py) to be able to reconstruct the (effectively) inclusive $D^{\*}$ MC (see Christos' [comment](https://github.com/umd-lhcb/lhcb-ntuples-gen/issues/127#issuecomment-1640388768) in his MC request issue for an overview of the samples), which will be used to get ghost efficiencies (transfer factors between fake and real $\mu$ stripping lines) for our misID. I'm not very familiar with the software/the reconstruction code, however, and I haven't been able to figure out what needs to be changed in the code in order to successfully reconstruct events.

@hadjichris Manuel and I thought maybe this would be a good thing for you to think about. I'll try to provide some more detailed guidance than this one (vague) comment soon, but for now maybe you can just think about this a bit.

As a note: I've just been trying to reconstruct a subsample of events locally (this is what we'd standardly been doing: reconstruct a small number of events locally to make sure everything is ok before submitting a large job to the GRID). Instructions for how to do this locally are [here](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/step1_davinci/) (it requires [installing Docker](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/installation/#install-docker-to-run-davinci-locally)).

**Comment by hadjichris** [comment]
@afernez Sure. I will go over the software and documentation and we can talk more about it on Tuesday.

**Comment by hadjichris** [comment]
For Apple M1 ARM-based system users: docker-machine is now deprecated. I found Colima to be a great replacement and you can easily connect the docker daemon with a simple command:
```
brew install docker docker-compose colima
colima start
```
Ready to docker!
```
docker pull umdlhcb/lhcb-stack-cc7:DaVinci-v45r6-SL
```

**Comment by hadjichris** [comment]
The JIRA ticket for the MC request of EventType `11774014` can be found [here](https://its.cern.ch/jira/browse/LHCBGAUSS-2603). As an option file they used [D02HH_TriggerFiltering](https://gitlab.cern.ch/lhcb-datapkg/WG/CharmConfig/-/blob/v3r137/options/MCFiltering/D02HH_TriggerFiltering.py).

**Comment by afernez** [comment]
I'll close this issue for now, since our plan is to instead request FullSim MC of `11774014`, given that the ReDecay samples produced used a charm trigger. The status of this should be followed in #127 (as well as older notes from Yipeng/Svende/Manuel in #111)
