### ISSUE TITLE
Understanding Phoebe's code

### ISSUE THREAD

**Issue by bflaggs** [umd-lhcb/lhcb-ntuples-gen#15]
This is my general understanding of Phoebe's files AddB.h and AddB.C. For AddB.h I am not sure whether I am understanding it correctly because I am not very familiar with header files yet (other than including them in the actual macros). For AddB.C my comments are mostly the text from the comments within the code that are stating what exactly the code is doing.

**AddB.h**

- header file for classes stored in a TTree

- class definition in this file was automatically generated by the ROOT utility TTree::MakeSelector()

- defines the different leaves and branches within the TTree along with defining the different functions to be called in AddB.C

- contains definitions for two additional functions, AddB::Init() and AddB::Notify()

- AddB::Init() -> called when selector needs to initialize a new tree or chain, branch addresses and branch pointers are established here

- AddB::Notify() -> called when a new file is opened, can be called for a new TTree in the TChain or when a new TTree is started, sets more branch addresses and pointers if certain criteria are met

**AddB.C**

- several functions within this macro, they occur in the macro in the order they are defined below

- AddB::PrintName() -> prints a string when fed a certain "partID"

- AddB::PrintBG() -> I believe this is used to print the decay (using text) although I am not sure

- AddB::Begin() -> called at start of a loop on the tree, described as "convenient place to create histograms", this procedure defines a large amount of histograms and has a lot of debugging information

- AddB::SlaveBegin() -> called after Begin(), when on PROOF called only on slave servers

- AddB::Process() -> called for each event, this is the function that reads in the data and fills the histograms, contains the "body" of the analysis on the data

- AddB::SlaveTerminate() -> called at end of loop on a tree, when on PROOF called only on the slave servers

- AddB::Terminate() -> called at end of loop on a tree, described as "convenient place to draw/fit histograms", presents results graphically or saves results to file

Overall, I am not sure what PROOF is as it is referred to in the descriptions of some functions although there is not a description of it. Also I am not sure what the use of SlaveBegin() and SlaveTerminate() is because in the SlaveBegin() function the only line of code is `TString option = GetOption();` and in the SlaveTerminate() function there are no lines of actual code, only comments.

**Comment by yipengsun** [comment]
I realized that Phoebe's code is a derived class of `TSelector`. A `TSelector` template class for a particular root file can be generated by:

```c++
TFile *f = TFile::Open("treefile.root")
TTree *t = (TTree *) f->Get("T")
t->MakeSelector("MySelector")
```

For more info about `TSelector`, refer to [1].


[1]: https://root.cern.ch/accessing-ttree-tselector

**Comment by yipengsun** [comment]
We'll split this HUGE task with smaller steps, such as #47. Closed.
