### ISSUE TITLE
ntuple generated with updated script doesn't agree with Phoebe's original ntuple

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#16]
We are comparing:
* Phoebe's ntuple: `/2012-b2D0MuXB2DMuNuForTauMuLine/data/sample/YCands_sample-mag_down-data.root`
* Our ntuple: `/2012-b2D0MuXB2DMuNuForTauMuLine/gen/YCands.root`

It seems that the muon momentum `muplus_P` and all its components have a ~5% deviation from Phoebe's. We need to investigate why.

**Comment by yipengsun** [comment]
@CoffeeIntoScience was able to adapt our `ntuple_options.py` to run on `DaVinci v36r1p2`. An interesting thing is that her ntuple now contains only 34 entries, whereas ours contains 243 entries.

**Comment by yipengsun** [comment]
I've updated 2 more comparisons here: https://umd-lhcb.github.io/lhcb-ntuples-gen/data/comparison_run1_RDst/comparison/

I'd say the the ntuples generated by the same script with different `DaVinci`'s look much more similar. This means that there's some bug in my `DaVinci` script in the sense that my script doesn't fully replicate @CoffeeIntoScience's functionality.

**Comment by yipengsun** [comment]
The main difference between ntuples generated by `DaVinci/v36r1p2` and `DaVinci/v42r8p1` seems to be in the isolation variables.

Phoebe suggested that this is likely due to the way the NoPID pions is set up.

**Comment by yipengsun** [comment]
@CoffeeIntoScience I've updated the comparison between the following variables generated by `DaVinci/v36r1p2` and `DaVinci/v42r8p1`:
```
Y_ISOLATION_Type
Y_ISOLATION_Type2
Y_ISOLATION_Type3
Y_ISOLATION_Type4
```

The comparison can be found [here](https://umd-lhcb.github.io/lhcb-ntuples-gen/data/comparison_run1_RDst/comparison/#y_isolation_type).

**Comment by yipengsun** [comment]
Before cutting on the `Y_ISOLATION_BDT` variables, for 2012 Mag Down data:
* Phoebe's has 442457 events
* Ours has 398512 events

After the `Y_ISOLATION_BDT < 0.15` cut:
* Phoebe's has 301503 events
* Ours has 258438 events

**Comment by yipengsun** [comment]
To disable `DecayTreeFitter`, I should replace the `TopSelection` option with `sel_B0`?
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/22b34a8e1851efd1d9cd9cade9bc6fb515f9325e/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst.py#L419-L435

Also, I start to remember things, and noticed this line:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/22b34a8e1851efd1d9cd9cade9bc6fb515f9325e/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst.py#L226-L227

I think I'll uncomment that for better backward compatibility.

**Comment by yipengsun** [comment]
Weird. The generated `.root` file cannot be opened by root.

**Comment by yipengsun** [comment]
@CoffeeIntoScience I've created a script for older version of DaVinci. You can download it from [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst-debug.py). It should be able to run on DaVinci/v36r1p2 without any editing.

**Comment by yipengsun** [comment]
I've updated ntuples generated with `DaVinci/v36r1p2` and `DaVinci/v42r8p1` without final refitting. The results are available [here](https://umd-lhcb.github.io/lhcb-ntuples-gen/data/comparison_run1_Dst/comparison/#comparison-between-davinci-v36r1p2-and-v42r8p1-without-refitting).

Now the momentum of the Kaons and Pions are fully agree, but the momentum of D0 still differs. This makes sense---D0 is reconstructed by `CombineParticle`, which will use some fitting tool.

**Comment by CoffeeIntoScience** [comment]
Can you rerun your script (just over like 300 events is fine) with the output level set to DEBUG and send me the log? (This used to be done via `from Gaudi.Configuration import *` followed by `MessageSvc().OutputLevel=DEBUG`)

**Comment by yipengsun** [comment]
The debug option you provided still works. I reran my script over exact 300 events with debug option enabled, and the log file is ~60 MB. The log file can be found [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/logs/20190926-reco_Dst-debug.log).

**Comment by yipengsun** [comment]
## `DaVinci` change logs regarding fit

Starting from `DaVinci/v36r1p2`, with `Phys/v19r8`.
End at `DaVinci/v42r8p1`, with `Phys/v23r9p1`.
 
| version | log |
|---|---|
| `v36r6` | In `Phys/Tesla v1r4`: Support refitted PV persistence. |
| `v37r2` | Include as patch packages `RelatedInfoTools`, `DaVinciTools`, `LoKiCore`, `LoKiPhys`, `LoKiAlgo` and `GaudiConf` |
| `v40r1` | Added `TrackSys` to used configurables. It configures the tracking related tools used by `LoKi::VertexFitter` and `DistanceCalculator` |
| `v42r4` | Allow to add selections directly to the list of `UserAlgorithms`. No need in the explicit appearence of `SelectionSequence` |

**Comment by CoffeeIntoScience** [comment]
Obviously the log comparison is still in-progress, but the first possibly-suspicious thing I see is we are connecting to different locations to fetch the latest DB tags and ending up with different ones. Mine if fetching
```dddb-20130929-1
cond-20141007```
while yours finds
```dddb-20171030-2
cond-20150409-1```

I think it would be worth your time to attempt to run forcing the DB tags that mine thinks are the "latest" to see if anything changes. I should also double check if the momentum scaling map is the same, though it looked okay on the first pass

**Comment by yipengsun** [comment]
Specifying tag doesn't help at all.

**Comment by yipengsun** [comment]
Phoebe found some duplicated tracks in our ntuples generated by both versions of DaVinci
![image](https://user-images.githubusercontent.com/33738176/66170623-ed818900-e612-11e9-8410-6c0ca4758470.png)

**Comment by yipengsun** [comment]
This is likely due to the fact that the `ms_velo_pions` are not set correctly to only pick VELO particles. Examples of correct usage can be found at: https://twiki.cern.ch/twiki/bin/view/LHCb/RestrippingMDST

(Dark Magic warning).

**Comment by yipengsun** [comment]
But the `trackSelector` is undefined.

**Comment by yipengsun** [comment]
I still see duplicated events.

**Comment by yipengsun** [comment]
The `trackSelector` and `updateDoD` are defined at: https://gitlab.cern.ch/lhcb/Stripping/blob/2017-patches/Phys/CommonParticlesArchive/python/CommonParticlesArchive/Stripping33r1/CommonParticles/Utils.py

**Comment by yipengsun** [comment]
After fixing a comparison bug, I see:
1. The momentum matching is only performed on events with a single candidate.
2. All momentum-matched tracks have the same type
3. Their BDT scores may differ (see attached csv files). The differences are observed in all track types (VELO, Forward, Upstream VELO)

[bdt_score_diff_dv36.txt](https://github.com/umd-lhcb/lhcb-ntuples-gen/files/3704371/bdt_score_diff_dv36.txt)
[bdt_score_diff_dv42.txt](https://github.com/umd-lhcb/lhcb-ntuples-gen/files/3704372/bdt_score_diff_dv42.txt)

**Comment by yipengsun** [comment]
@CoffeeIntoScience I've included more Y-branches in the csv files linked above. I still think the values are mostly similar.

**Comment by CoffeeIntoScience** [comment]
just for future reference, y is more sensitive than x to fitting differences because the uncertainty in that direction is typically greater (less precise downstream measurements).

Hmmm.

would still like to see PT and maybe, I guess, IPCHI2 of the Dst's slow pion

**Comment by yipengsun** [comment]
I've updated the track type vs chi^2 plots. Indeed there's a significant shift for VELO only tracks.

Once Phoebe uploads her new ntuple to the shared folder, I'll redo plots for ntuples with both refitting and momentum rescaling disabled.

**Comment by yipengsun** [comment]
We've decided to move up to `DaVinci/v45`, the recommended version for both run 1 and 2, and see if we still have these disagreements.

The progress will be tracked at umd-lhcb/TupleToolSemileptonic#1.

**Comment by yipengsun** [comment]
@CoffeeIntoScience I've finally updated my local `DaVinci` to `v45r3`, the recommended version for all run 1 and run 2 analyses. I regenerated the no-refit ntuple, and made comparisons between that and v36, v42 ntuples. 

The result is: v45 is still different from v36, v45 is **identical** to v42. Please take a look at:
https://umd-lhcb.github.io/lhcb-ntuples-gen/data/comparison_run1_Dst/comparison/#comparison-between-davinci-v36r1p2-and-v45r3-without-refitting

**Comment by CoffeeIntoScience** [comment]
okaaay? I didn't think we expected anything different in these comparisons?

**Comment by yipengsun** [comment]
I thought the idea (your idea) was that given v45 is the officially
recommended version for both run 1 and run 2, it may automatically fallback
to the previous algorithm.

**Comment by CoffeeIntoScience** [comment]
Hmmm. I guess that was not impossible. I don't know where the switch to the simplified geometry is done, and its very possible its not easily togglable.

Anyway, the bigger point is that lack of better agreement here shouldn't be a road block and you should resume trying to get efficiencies from the inclusive MC samples and close the loop on this factor of 5 as quickly as is reasonable

**Comment by CoffeeIntoScience** [comment]
Obviously the isolation differences will be an issue going forward -- it might just be that you need to retrain the BDT for Run2 due to this difference, because the change does seem to have affected VELO and everything else differently

**Comment by yipengsun** [comment]
We've tried to use DaVinci v45r3, and we have the same "problem". Closed for now, as this problem might be resolved by retraining the BDT for run 2.
