### ISSUE TITLE
Questions on MC DaVinci script and generated ntuples

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#18]
I have the following questions In Phoebe's original `DaVinci` script for Dstar reconstruction `YCandReco3.py`:
* Line 133-143: `Bd` seems to be `Bu`, and the `CombinationCut` and `MotherCut` are different from data `DaVinci` options.
* Line 186-188: `trackSelector` and `updateDoD` not explicitly defined or imported.
* Line 231: I can't find `TupleToolApplyIsolationSoft`
  > `TupleToolApplyIsolationSoft` is just configured `TupleToolApplyIsolation`

@CoffeeIntoScience please take a look.

**Comment by yipengsun** [comment]
I'm also confused about these 2 scripts. Apparently I was looking at the wrong scripts. But the "correct" script was reconstructing B -> D0, instead of B -> D* at the end.

**Comment by CoffeeIntoScience** [comment]
Regarding the scripts. I suggested to look at YCandRecoD04 because it has the latest MC truth matching stuff which I guess I never bothered to add to YCandReco3 (the Dst script). Probably the Dst loose DeltaM cut is harsh enough that it's less important here.

**Comment by CoffeeIntoScience** [comment]
On the original questions I don't understand some of the problems here. I thought you had the Isolation stuff working on your end?

**Comment by yipengsun** [comment]
I have `TupleToolApplyIsolation`, but not `TupleToolApplyIsolationSoft`.

**Comment by CoffeeIntoScience** [comment]
Look at 2 lines above

`tuple.Y.addTool(TupleToolApplyIsolation,name="TupleToolApplyIsolationSoft")`

It's still just `TupleToolApplyIsolation`

**Comment by yipengsun** [comment]
Also, in `YCandRecoD04.py`, you don't have `(TRCHI2DOF < 4)` cut for `K+` and `pi-`, but you do have this in the data `DaVinci` script. So should I just drop this cut?

**Comment by CoffeeIntoScience** [comment]
You can drop that. It was in the stripping but tracks don’t become “best tracks” and get promoted to protoparticles without chi2/dof < 3

You see manual cuts in lots of older stripping lines because it wasn’t a standard in older reco versions

**Comment by CoffeeIntoScience** [comment]
Check your input lists for your selections. E.g.:

`sel_D0 = Selection(
    'SelMyD0',
    Algorithm=algo_D0,
    RequiredSelections=[sel_charged_K, sel_charged_Pi]
)`

but

`sel_charged_K = Selection(
    'SelMyChargedK',
    Algorithm=FilterInTrees('MyChargedK', Code="(ABSID == 'K+')"),
    RequiredSelections=[sel_stripped_filtered]
)`

so you're implicitly adding the stripping filter because you're trying to use as input Kaons from the stripping line that doesn't exist.

Maybe you've already fixed this though?

**Comment by yipengsun** [comment]
Now I just use `AutomaticData` locations for K, Pi, and Mu, and it generates a ntuple.

Running over 30 events, the ntuple retains 8 events.

**Comment by yipengsun** [comment]
Some warnings were found in the `DaVinci` log:
```
LoKiSvc.REPORT      ERROR LoKi::PhysMCParticles::MCTreeMatch:   No valid relation table at 'Relations/Rec/ProtoP/Upstream' [SelMyBd] StatusCode=FAILURE
LoKiSvc.REPORT      ERROR The   ERROR message is suppressed : 'LoKi::PhysMCParticles::MCTreeMatch:      No valid relation table at 'Relations/Rec/ProtoP/Upstream'

CaloClusterMCTruthWARNING CaloClusterMCTruth:: No MC information for the cluster is found StatusCode=FAILURE
```

I'll investigate more once the run finishes.

**Comment by CoffeeIntoScience** [comment]
it shouldnt be terribly frequent, but sometimes the truth matching just dies for some events. not much to do on that. at least if its just upstream tracks or CALO stuff that's not a huge deal since you aren't using those

**Comment by yipengsun** [comment]
The generated MC ntuples missing mass distribution is a Dirac delta at 0. Something is wrong. Should I use the same `weightSoft.xml` for both data and MC?

**Comment by yipengsun** [comment]
Also, it took 4+ hrs to run over 2 DST files with a total size of 7 GB. Is this normal?

**Comment by CoffeeIntoScience** [comment]
> The generated MC ntuples missing mass distribution is a Dirac delta at 0. Something is wrong. I see the mass distribution of Muon, Pion, and Kaon are all just very sharp peaks.
Remember basic particle masses are assumed, not measured. How does the D0 mass look? My instinct is that the missing mass tuple tool is failing in some way, though why they would choose 0 as the failure/default is beyond me
> Should I use the same weightSoft.xml for both data and MC?
Yes. Though this is irrelevant for missing mass
> How is the momentum so precise, even with smear applied?
How do you know it's precise, except for the possibly-buggy rest frame tool?

> Also, it took 4+ hrs to run over 2 DST files with a total size of 7 GB. Is this normal? The generated ntuple is ~20 MB. I'm running DaVinci locally on a SSD, and this seems a bit slow to me.

This seems pretty normal, yeah. Remember the vast difference in 'interesting event density' between data DSTs and (Filtered!) MC DSTs. When I run on the grid I generally split to 1 or 2 files per job

**Comment by yipengsun** [comment]
It was a false alarm. The binning of the missing mass was wrong so almost all events are cramped into a single bin. After plotting it, the missing mass distribution is in agreement with expected signal missing mass:
![Mmiss](https://user-images.githubusercontent.com/33738176/61149247-b20d6d80-a4ae-11e9-803d-288bddd911e5.png)
