### ISSUE TITLE
Muon sources for reco

### ISSUE THREAD

**Issue by CoffeeIntoScience** [umd-lhcb/lhcb-ntuples-gen#25]
The snippet referenced below still shows some fundamental misunderstanding and misuse of the term "stripped" to refer to muons. What is there works for cutflow, but I thought I'd spawn a new issue for longer term things.

"Stripped muons" should mean *ONLY* muons used in the reconstruction of the D0mu combination by the stripping algorithm. Nothing further. In the language of the code, it means the muons are not coming from the StdWhatever lists, but are coming from FilterInTrees like the pi and K.

"TIS filtered muons" is what you mean by stripped muons in your comments, and I'd like you to stop using "stripped" to refer to them because you are confusing yourself as well as the rest of us! "TIS filtered muons" should be used to refer to muons after your TisTosParticleTagger, and it is **TOTALLY INDEPENDENT** of whether these are stripped muons or standard muons.

The confusion you're having is because whether or not you want to TIS filter the muons can be correlated with whether you have a stripping line to get muons from FilterInTrees or not. For example, for the Run1 analysis the productions which are filtered *do not* have a stripping line, and also we did not want to download candidates with muons that did not pass the TIS filter. So therefore you have the combination Unstripped and Tis filtered you have in your code. But the reasons are different! It is "unstripped" because the stripping was not run on this MC production. It is "TIS filtered" because the productions are large and we have no plans to use events that do not pass this filter, so we want to save local disk space.

Contrarywise, in data, we always have a stripping line. Further, it can sometimes be useful to use the TOS muons as a control sample for data/MC comparisons with unfiltered monte carlo. So these may be "Stripped" and "not TIS filtered", which i believe is what I recommended at first, but "Stripped" and "TIS filtered" is a perfectly valid combination which I also have used and do use! They are independent.

I hope this clarifies things. The practical upshoot of the issue is you should have possible all 4 pathways and decide individually per sample which combination of "stripped" and "TIS filtered" is appropriate

@manuelfs @CoffeeIntoScience Please take a look to see if now the implementation is correct:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/f86f92cabf5bb9bed094eaf3bf806e3a6c7abafd/run2-b2D0MuXB2DMuForTauMuLine/reco_Dst.py#L162-L186

**Comment by yipengsun** [comment]
The cut flow study is in [`reco_Dst-cut_flow.py`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst-cut_flow.py). 

The snippet you listed is a legacy: I had that misunderstanding 1 or 2 weeks ago, but that has been fixed. I just haven't updated that script yet. Will do that soon.

**Comment by yipengsun** [comment]
I also should be more explicit on **STRIPPED** and **TIS-FILTERED**.

**Comment by CoffeeIntoScience** [comment]
oof, gotcha. I took the timing to be similar to the email I got over the weekend instead of reading timestamps like I should have

srry

**Comment by yipengsun** [comment]
I updated various `reco_Dst-*` scripts. @CoffeeIntoScience @manuelfs Is my comments clear now?

**Comment by yipengsun** [comment]
@manuelfs I've updated latest comments. Please take another look. If everything looks OK, then please close this issue.

**Comment by yipengsun** [comment]
@manuelfs I've combined the `reco_Dst*` script into one. Now you just need to check one script.

**Comment by yipengsun** [comment]
The latest progress is tracked in #34.
