### ISSUE TITLE
MC cocktail samples used for Runs 1 and 2 cutflow

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#26]
We are studying the differences between Runs 1 and 2 conditions and reconstruction with Bd_D0Xmunu, D0=cocktail Monte Carlo (ID **11874091**). The samples are
- Run 1 (2011): `/MC/2011/11874091/Beam3500GeV-2011-MagDown-Nu2-Pythia8/Sim08h/Digi13/Trig0x40760037/Reco14c/Stripping20r1NoPrescalingFlagged`
- Run 2 (2016): `/MC/2016/11874091/Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8/Sim09b/Trig0x6138160F/Reco16/Turbo03/Stripping26NoPrescalingFlagged`

The python scripts to download the files, also specifying the production scripts, can be downloaded from [2011](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/data/mc-mag_down-py8-sim08h-Bd2D0XMuNu-D0_cocktail/MC_2011_11874091_Beam3500GeV2011MagDownNu2Pythia8_Sim08h_Digi13_Trig0x40760037_Reco14c_Stripping20r1NoPrescalingFlagged_ALLSTREAMS.py) and [2016](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-b2D0MuXB2DMuForTauMuLine/data/mc-mag_down-py8-sim09b-Bd2D0XMuNu-D0_cocktail/MC_2016_11874091_Beam6500GeV2016MagDownNu1.625nsPythia8_Sim09b_Trig0x6138160F_Reco16_Turbo03_Stripping26NoPrescalingFlagged_ALLSTREAMS.py). 

The branching fractions and form factors used for the generation of these samples can be found in its `.dec` file at https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/blob/v30r43/dkfiles/Bd_D0Xmunu,D0=cocktail.dec.

In general, you can find the `.dec` file for a given MC ID at https://lhcb.github.io/starterkit-lessons/first-analysis-steps/bookkeeping.html

**Comment by yipengsun** [comment]
Should I download the option files for all dst files in the future?

**Comment by manuelfs** [comment]
I think it can be helpful. That way we have the path for additional files if we need them, and can quickly check the configuration scripts.

Best,
Manuel




On Mar 24, 2020, at 4:07 AM, Yipeng Sun <notifications@github.com<mailto:notifications@github.com>> wrote:



Should I download the option files for all dst files in the future?

**Comment by yipengsun** [comment]
OK. Will do that for all dst files in the future.

**Comment by manuelfs** [comment]
Trying to retrieve the `.dec` file for this cutflow, I realized that it was deprecated due to a small mistake
- The old cocktail (ID **11874091**) https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/blob/v30r43/dkfiles/Bd_D0Xmunu,D0=cocktail.dec had a `B0 -> MyD0	pi-	mu+	nu_mu` decay
- The new cocktail (ID **11874094**) https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/v30r59/dkfiles/Bd_D0Xmunu,D0=cocktail.dec has this fixed to `B0 -> MyAntiD0	pi-	mu+	nu_mu`

The normalized branching fractions are
```
Decay B0sig
  0.6463   MyD*-  mu+  nu_mu              HQET 2.0 1.207 0.908 1.406 0.853;
  0.1468   MyD_1-  mu+  nu_mu             PHOTOS ISGW 2.0;
  0.0610   MyD'_1-  mu+  nu_mu            PHOTOS ISGW 2.0;
  0.0590   MyD_0*-  mu+  nu_mu            PHOTOS ISGW 2.0;
  0.0420   MyD*-  Mytau+  nu_tau          PHOTOS ISGW 2.0;
  0.0372   MyD_2*-  mu+  nu_mu            PHOTOS ISGW 2.0;
  0.0054   MyD*-  pi0  mu+  nu_mu         PHOTOS GOITY_ROBERTS;
  0.0023   MyAntiD0  pi-  mu+  nu_mu      PHOTOS GOITY_ROBERTS;
Decay MyD0
  1.0000   K-  pi+      PHOTOS PHSP;
Decay MyD*+
  1.0000   MyD0  pi+      PHOTOS VSS;
Decay MyD*0
  0.6190   MyD0  pi0        PHOTOS VSS;
  0.3810   MyD0  gamma      PHOTOS VSP_PWAVE;
Decay MyD_0*+
  1.0000   MyD0  pi+      PHOTOS PHSP;
Decay MyD_1+
  0.6250   MyD*+  pi+  pi-      PHOTOS PHSP;
  0.2500   MyD*0  pi+           PHOTOS VVS_PWAVE 1.0 0.0 0.0 0.0 0.0 0.0;
  0.1250   MyD*+  pi0           PHOTOS VVS_PWAVE 1.0 0.0 0.0 0.0 0.0 0.0;
Decay MyD'_1+
  0.6667   MyD*0  pi+      PHOTOS VVS_PWAVE 1.0 0.0 0.0 0.0 0.0 0.0;
  0.3333   MyD*+  pi0      PHOTOS VVS_PWAVE 1.0 0.0 0.0 0.0 0.0 0.0;
Decay MyD_2*+
  0.5426   MyD0  pi+       PHOTOS TSS;
  0.3049   MyD*0  pi+      PHOTOS TVS_PWAVE 0.0 0.0 1.0 0.0 0.0 0.0;
  0.1525   MyD*+  pi0      PHOTOS TVS_PWAVE 0.0 0.0 1.0 0.0 0.0 0.0;
Decay Mytau-
  1.0000   mu-  nu_tau  anti-nu_mu      PHOTOS TAULNUNU;
```
