### ISSUE TITLE
Checking unified DaVinci script reco_Dst.py

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#34]
I went through the unified DaVinci scripts `reco_Dst.py` for [Run 1](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b685e2a0cb7d0e6814a2077bc4777d698bb3e1e0/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst.py#L1) and [Run 2](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b685e2a0cb7d0e6814a2077bc4777d698bb3e1e0/run2-b2D0MuXB2DMuForTauMuLine/reco_Dst.py#L1) committed on April 24. I have a few comments, and a summary of the scripts at the end

### Differences with old script

The only meaningful difference I found with respect to the [`reco_DST-cutflow.py` script](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/6c44f12f0109f75fd31d9e094ea885417b2ce05e/run2-b2D0MuXB2DMuForTauMuLine/reco_Dst-cut_flow.py) from 0.8.2 is the use of `HLT_PASS_RE` in Run 2, changed to `HLT_PASS` now. The former checks for regular expressions whereas the latter looks for an exact match, so it should be tighter. Yipeng sees the number of B candidates in Run 2 decrease from 6738 to 6732, though some other effects could affect this. In a low-statistics local test, only changing this results in 342 B's either way.

### Bug on non-CUTFLOW ntuples

In Run 1, the `sel_stripped_charged_K` and `sel_stripped_charged_Pi` lists are using muons (`sel_stripped_Mu_filtered_evt`) when not for CUTFLOW, so this should be changed to `pr_stripped` like in Run 2. 

In general, I don't think we care about TIS filtering muons as of now, so we probably should remove all references to these muons from the script.

### Things to keep in mind for when we move beyond CUTFLOW

There are a number of assumptions and missing selections that will become a problem when we start making ntuples from other samples. The general strategy should be to have all the stripping cuts fully implemented in the script, so that they are applied even when the MC is non-flagged. These cuts should be validated by running on flagged MC (for instance, the cocktail), and comparing ntuples straight from the stripping lists, and from the original lists after applying these cuts.

- The `D0` in Run 1 is missing `(ADAMASS('D0') < 100.0 *MeV) & (ACHILD(PT,1)+ACHILD(PT,2) > 1400.0 *MeV)` and `(SUMTREE( PT, ISBASIC )> 1400.0 * MeV) &(ADMASS('D0') < 80.0 *MeV) & (VFASPF(VCHI2/VDOF) < 4.0) & (BPVVDCHI2 > 250.0) & (BPVDIRA> 0.9998)`
- The stripping cuts for the muon are being applied to the MC but they should also be applied to data
- `algo_B0` in data is missing the `TRGHOSTPROB < 0.5) &(MIPCHI2DV(PRIMARY)>45) & (TRCHI2DOF < 3.0)` that the MC has, and `P>3.0*GeV` should also be added to match the stripping
- Currently, in Run 1 MC CUTFLOW we are using the stripping line from Run 2 (without a `Nu`). This may be the case in other newer Run 1 samples, so we need to keep an eye on that
- In Run 1, the data is stripped and filtered by HLT, and I think we want both in MC as well (stripping only possible when flagged)

### Questions

- Why the additional cuts for MC of `(mcMatch('[^K+]CC')) & (P > 2.0*GeV) & (MCSELMATCH(MCNINANCESTORS(BEAUTY) > 0))`
- For Run 2, why doesn’t it work to add all non-`L0HadronDecision` L0 lines to only the Y?
- We don't need TIS muon filtering now, but how do `TisTosSpecs={'L0Global%TIS': 0}` and `TIS('L0.*', 'L0TriggerTisTos’)` compare? Why was it changed from one to the other?

### Outline of the DaVinci scripts

* #### Configure DaVinci #
    * Set EvtMax = -1, SkipEvents = 0, PrintFreq = 100
* #### Customize DaVinci main sequence #
    * Loads ProtoParticles, StdNoPIDsVeloPions
    * Does track scaling (data) and smearing (MC)
* #### Define pre-filters #
    * Defines the stripping line and cuts with HLT_PASS
        * `b2D0MuXB2DMuForTauMuLine` for Run 2 and Run 1 and flag `CUTFLOW` (2011 MC), `b2D0MuXB2DMuNuForTauMuLine` for other Run 1
    * In Run 1, HLT cut on `Hlt2CharmHadD02HH_D02KPi`
    * In Run 1
        * Strips CUTFLOW
        * Strips and HLT data
        * Nothing for MC
    * In Run 2
        * Strips for data and CUTFLOW
        * Nothing for MC
* #### Particle references #
    * `pr_stripped` has the stripped particles, which are typically in `/Event/Semileptonic`, but in the cocktail in `AllStreams/Phys`
    * `pr_charged_K`, `pr_charged_Pi`, and `pr_Mu` are `NoPID`, but `pr_all_Pi` are `Loose`
* #### Define simple selections #
    * `sel_stripped_Mu_filtered_evt` are stripped muons with an L0 cut
        * In run 1 these are used for non-cutflow, but in Run 2 they are not used at all. Why?
        * These muons are also the selection for stripped K and Pi, which seems like a bug
    * Defines the stripped K, Pi, and Mu lists
    * `sel_unstripped_tis_filtered_Mu` have a `TisTosSpecs={'L0Global%TIS': 0}` cut, different from `sel_stripped_Mu_filtered_evt`
    * If it is data or CUTFLOW, use the standard stripped K, Pi, and Mu else, use the NoPID lists
        * except for muons in Run 1, where they use the `sel_unstripped_tis_filtered_Mu`
* #### Define algorithms #
    * Apply the actual stripping cuts, in case stripping flags do not exist 
        * The K, pi match, as well as the combination cuts for D0 in Run 2, but not in Run 1
    * Builds the D* with (same for Run 1 and 2)
        *  `'pi+': '(MIPCHI2DV(PRIMARY) > 0.0) & (TRCHI2DOF < 3) & (TRGHOSTPROB < 0.25)’`
        * `(ADAMASS('D*(2010)+') < 220*MeV)`
        * `(ADMASS('D*(2010)+') < 125*MeV) &(M-MAXTREE(ABSID=='D0', M) < 160*MeV) &(VFASPF(VCHI2/VDOF) < 100)`
    * Builds the D* with the wrong sign pion, and B0 with wrong sign muon
    * Builds the B0 with `(AM < 10200*MeV)` and `(M < 10000*MeV) & (BPVDIRA > 0.9995) & (VFASPF(VCHI2/VDOF) < 6.0)`
        * Also if MC `(mcMatch('[^mu+]CC')) & (TRGHOSTPROB < 0.5) &(MIPCHI2DV(PRIMARY)>45) & (TRCHI2DOF < 3.0)
            * These are the stripping cuts minus `P>3.0*GeV`, so probably should be applied to the data as well
* #### Define selections #
    * Puts together the algorithms and particle lists for `SelMyD0`, `SelMyDst`, `SelMyB0`, `SelMyRefitB02DstMu` and WS
        * Identical between Run 1 and 2
* #### Define selection sequences #
    * `SeqMyB0` with the refitted B, and adds the WS sequences if it is data or not CUTFLOW
* #### Define n-tuples #
    * Defines what to add to the ntuples with TupleTools
    * A list of trigger lines is defined for all particles `trigger_list_global` and for the B `trigger_list_Y`

**Comment by yipengsun** [comment]
Trying to answer your questions:

1. That was blindly copied from Phoebe's. However, looking at [this](https://lhcb.github.io/bender-tutorials/simulation/mcmatch.html), I think here we are requiring that the MC particles **MUST** make contribution to the reconstructed particles.

2. When adding/configure `TupleToolTisTos` on `Y` only, the configuration for `TupleToolTrigger` gets completely overwritten. No idea why, but this is what I see locally. That is why in [this post](https://github.com/umd-lhcb/lhcb-ntuples-gen/issues/33#issuecomment-618253266), #33, that certain branches get removed. 

    Note that these branches, generated by `TupleToolTrigger`, can't be re-added because `TupleToolTrigger` doesn't allow per-particle configuration.

3. I think, they are different because we use different filters: `FilterInTree` and `TisTosParticleTagger`. 

    Note that for `sel_stripped_Mu_filtered_evt`, we are only keeping events that contains a Muon and has any L0 trigger decision. This only applied to data, as this MC is not-stripped.

    For `sel_unstripped_tis_filtered_Mu`, we are just TIS-filtering un-stripped Muon, and is only applied to some MC.

**Comment by yipengsun** [comment]
I think the _Outline_ section could well be part of the documentation to bootstrap newcomers. Cc #29.

**Comment by manuelfs** [comment]
I think we have answers to my questions above
- Why the additional cuts for MC of `(mcMatch('[^K+]CC')) & (P > 2.0*GeV) & (MCSELMATCH(MCNINANCESTORS(BEAUTY) > 0))`
  - Phoebe says that they are to avoid including also the combinatorial `D*munu` events and speed things up by an _enormous amount_
- For Run 2, why doesn’t it work to add all non-`L0HadronDecision` L0 lines to only the Y?
  - I think Yipeng told me but I forgot... It may be that it does work for L0, but not for HLT, which is needed in Run 2
- We don't need TIS muon filtering now, but how do `TisTosSpecs={'L0Global%TIS': 0}` and `TIS('L0.*', 'L0TriggerTisTos’)` compare? Why was it changed from one to the other?
  - One is applied at a event level, and the other at the particle level

**Comment by yipengsun** [comment]
## Checks for run 1 `reco_Dst.py`

| mode | updated? | # of events |
|---|---|---|
| `cutflow_mc` | N | 429 |
| `cutflow_mc` | Y | 430 |
| `cutflow_mc-no_stripping` | Y | 4835 |

**Comment by yipengsun** [comment]
Well, the `master` branch definitely is bugged, as the difference between old and new `data` ntuple is HUGE. I've already tried to switch back to `EventPreSelector`, but they yielded the same ntuple, so this is not due to filter stuff. 

I'm going back in (tagged) history to debug this.

**Comment by yipengsun** [comment]
@manuelfs finally, I made a script to check common candidates between two ntuples and write a `make` rule to automatically check whether _bare_ ntuples agree with _dv-strip_ or not.

Please take a look at:

1. Reconstruction scripts for run 1 and 2
2. `Makefile`
3. Sample ntuples with `bare` and `dv_strip` in their filenames in the `samples` folders
4. `Dst-stripping.yml` in the `postprocess` folders

Then you can run `make test-cutflow-run1` and `make test-cutflow-run2`.

If you think these checks are good enough, I think we can close both this and #41.

**Comment by manuelfs** [comment]
Validated the stripping cuts in the DaVinci script in #41 indeed.
