### ISSUE TITLE
Generation of unstripped ntuples for studying stripping selection

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#37]
We need to generate cocktail MC ntuples without the stripping cuts applied. These ntuples will be at most 2 GB each for 2011 and 2016, and will allow us to study the effect of stripping, trigger efficiency before stripping, and have a better feel for a number of distributions. We should take advantage to have better names for the branches in our step 1 ntuples
- `Y` → `b0`
- `D0` → `d0`
- `Kplus` → `k`
- `piminus0` → `pi`
- `muplus` → `mu` 
- `Dst_2010_minus` → `dst`
- `piminus` → `spi` for _slow pion_

We should also start organizing each of our ntuple productions in centrally stored folders, typically with the date and some identifier, eg `2020-05-04_no_stripping`.  I checked that our ntuples have the appropriate branches to apply the [stripping cuts](https://github.com/umd-lhcb/lhcb-ntuples-gen/issues/22). In some cases, the branches are named differently (LOKI definitions in [twiki](https://twiki.cern.ch/twiki/bin/view/LHCb/LoKiHybridFilters))
- `MIPCHI2DV(PRIMARY)` → `IPCHI2_OWNPV`
- `TRGHOSTPROB` → `TRACK_GhostProb`
- `ADAMASS` → `MM`
- `VFASPF(VCHI2/VDOF` → `D0_OWNPV_CHI2/D0_OWNPV_NDOF`
- `BPVVDCHI2` → `D0_FDCHI2_OWNPV`
- `BPVDIRA` → `D0_DIRA_OWNPV`

Some explanation of what we've learned so far. We have spent some time trying to understand the increase in efficiency in Run 2 vs Run 1, about 250% in MC and 300% in data. The [MC cutflow](https://umd-lhcb.github.io/lhcb-ntuples-gen/data/cutflows/Dst_run1_vs_run2/overview/) shows that the key increases occur at
- Stripping +28%
- L0 +22%
- HLT1 +37%
- HLT2 +47%

It was expected to have efficiency increases in the stripping (looser selection), and HLT2 (new specific trigger line). Perhaps in HLT1 as well if the new TrackMVA lines are significantly better, but the increase in efficiency in L0 is surprising, given that the [cuts are tighter in Run 2](https://github.com/umd-lhcb/lhcb-ntuples-gen/issues/36). 

The comparison of [pT distributions](https://umd-lhcb.github.io/lhcb-ntuples-gen/data/cutflows/Dst_run1_vs_run2/detail/) shows that the increased L0/HLT1 efficiencies probably come from the harder pT, which partly may come from the higher collision energy, but partly from the harder pT in the Run 2 stripping line. As the plot below shows, Run 1 has a cut on `ACHILD(PT,1)+ACHILD(PT,2)` at 1.4 GeV, while it is at 2.5 GeV in Run 2. 

![Kplus_PTppiminus0_PTd1000__shapes_lin](https://user-images.githubusercontent.com/4977423/80926172-858b5080-8d63-11ea-985a-dbb4c5edd831.png)

This cut clearly has higher efficiency in Run 1, where it looks close to 100% efficient, than in Run 2, where a significant portion of D0Xmunu is cut out. Thus, the rest of the Run 2 stripping line has to be significantly looser.

Thus, the increase in trigger efficiency may be mostly an artefact of requiring harder pT during stripping, and applying the triggers afterward. We will be able to change this order using the unstripped ntuples.

By the way, there are 3 events in Run 2 below the cut. 
```
root [43] c.Scan("eventNumber:runNumber:Kplus_PT+piminus0_PT", "Kplus_PT+piminus0_PT<2500")
************************************************
*    Row   * eventNumb * runNumber * Kplus_PT+ *
************************************************
*     4038 *    493968 *   5617624 * 2499.8645 *
*     4070 *    537694 *   5617697 * 2488.2532 *
*     5232 *    438307 *   5617531 * 2498.9153 *
************************************************
```
I wonder whether they belong to an event which had multiple candidates, one of which was above the cut. The repeated events are not in the ntuple though.

**Comment by yipengsun** [comment]
> We should also start organizing each of our ntuple productions in centrally stored folders, typically with the date and some identifier, eg `2020-05-04_no_stripping`. I checked that our

I think we don't need to explicitly have a data in our ntuple filenames, because Ideally **all** our ntuples are the latest ones and are ready to use, so we don't care about production date.

Should there be an update to any of the generated ntuples, we just update it in-place, and let the `git-annex` handle the versioning (if we have enough disk space, which I think we do, because currently the annex repo is stored in a 1 TB disk, and it has basically nothing but this repo and some random files that I can delete).

**Comment by yipengsun** [comment]
As of showing tag messages (for annotated, the annotated message, for un-annotated, just the commit message), here's a link: https://stackoverflow.com/questions/5358336/how-to-list-all-tags-along-with-the-full-message-in-git

**Comment by yipengsun** [comment]
For the renaming of the particles: I'm trying to rename the following particles in the **WRONG SIGN** tree: 
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/54b093219868fab45e88265bb3378e82d621872f/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst.py#L649-L665

Apparently Phoebe didn't change the branch name. This is just a reminder.

**Comment by yipengsun** [comment]
Side note: I decide to apply filters at DaVinci level, instead of selection level. See https://github.com/umd-lhcb/lhcb-ntuples-gen/issues/31#issuecomment-615322763 for more details.

**Comment by yipengsun** [comment]
I'm not sure if this is doable. I removed the `MotherCut, DaughterCuts, CombinationCut` from `algo_Dst`, but I get the following error message:
```
ToolSvc.HybridF...  ERROR  PyError Type      : <type 'exceptions.SyntaxError'>
ToolSvc.HybridF...  ERROR  PyError Value     : invalid syntax (<string>, line 26)
ToolSvc.HybridF...   INFO Filename: <string>
ToolSvc.HybridF...   INFO Lineno  : 26
ToolSvc.HybridF...   INFO offset  : 18
ToolSvc.HybridF...   INFO text    : _code=Configure me!

ToolSvc.HybridF...   INFO msg     : invalid syntax
ToolSvc.HybridF...   INFO message :
ToolSvc.HybridF...   INFO prntfal : None
ToolSvc.HybridF...  ERROR  Python error in Code
Python error  : invalid syntax (<string>, line 26)
PyErr msg     : invalid syntax
 Line #26
       _code=Configure me!
                        ^
ToolSvc.HybridF...  ERROR Native Python printout to stderr
  File "<string>", line 26
    _code=Configure me!
                     ^
SyntaxError: invalid syntax
ToolSvc.HybridF...  ERROR End of native Python printout to stderr
ToolSvc.HybridF...  ERROR  Error has occured in Python: the problematic code is :
ToolSvc.HybridF...  ERROR # ==============================================================================
# python pseudomodule, generated for the tool 'ToolSvc.HybridFactory'
# ==============================================================================
# Arguments:
# 	code    = 'Configure me!'
# 	actor   = 'LoKi.Hybrid.Engine()'
# 	modules = [ 'LoKiPhys.decorators' , 'LoKiProtoParticles.decorators' , 'LoKiArrayFunctors.decorators' , 'LoKiCore.functions' , 'LoKiCore.math' ]
# 	lines   = [  ]
# 	context = '
##! '
# ==============================================================================
##        MODULES :
from LoKiPhys.decorators import *
from LoKiProtoParticles.decorators import *
from LoKiArrayFunctors.decorators import *
from LoKiCore.functions import *
from LoKiCore.math import *
## End of MODULES
## The ACTOR :
_actor=LoKi.Hybrid.Engine()
##        LINES :
## end of LINES
##        CONTEXT :
## End of CONTEXT
##        CODE :
_code=Configure me!
## End of CODE :
sc=_actor.process('ToolSvc.HybridFactory',_code)
# ==============================================================================
# The END
# ==============================================================================

ToolSvc.HybridF...  ERROR LoKi::Hybrid::Tool::  Error has occured in Python  [SelMyDst] StatusCode=FAILURE
ToolSvc.HybridF...  ERROR LoKi::Hybrid::Tool:: Error from LoKi::Hybrid::Base::executeCode [SelMyDst] StatusCode=FAILURE
ToolSvc.HybridF...  ERROR LoKi::Hybrid::Tool:: Invalid object for the code 'Configure me!' [SelMyDst] StatusCode=FAILURE
SelMyDst            ERROR CombineParticles:: Unable to  decode 'mother'-cut: Configure me! StatusCode=FAILURE
SelMyDst            ERROR CombineParticles:: The error from decodeAlLCuts StatusCode=FAILURE
SelMyDst            ERROR CombineParticles:: Error from updateMajor StatusCode=FAILURE
SeqMyB0             ERROR GaudiSequencer:: Can not initialize SelMyDst StatusCode=FAILURE
DaVinciUserSequ...  ERROR GaudiSequencer:: Can not initialize SeqMyB0 StatusCode=FAILURE
DaVinciAnalysisSeq  ERROR GaudiSequencer:: Can not initialize DaVinciUserSequence StatusCode=FAILURE
FilteredEventSeq    ERROR GaudiSequencer:: Can not initialize DaVinciAnalysisSeq StatusCode=FAILURE
DaVinciEventSeq     ERROR GaudiSequencer:: Can not initialize FilteredEventSeq StatusCode=FAILURE
EventLoopMgr        ERROR Unable to initialize Algorithm: DaVinciEventSeq
ServiceManager      ERROR Unable to initialize Service: EventLoopMgr
ApplicationMgr      ERROR Application Manager Terminated with error code 1
```

**Comment by yipengsun** [comment]
The main problem is, some of the cuts require configuration:
```
_code=Configure me!
```

As usual, [TWiki](https://twiki.cern.ch/twiki/bin/view/LHCb/DaVinciTutorial4#2_3_CombineParticles) doesn't say if these cuts are required.

**Comment by yipengsun** [comment]
But according to the [LoKi functor TWiki on `ALL`](https://twiki.cern.ch/twiki/bin/view/LHCb/LoKiHybridFilters#ALL_All), if I don't want any cuts, I can just use `ALL`. 

But it's not the case here.

**Comment by yipengsun** [comment]
Let me summarize:

1. We don't want to apply any cuts to reconstruct _unstripped_ ntuples
2. Naively removing cuts from selection algorithms doesn't work, because these cuts require configuration. See `_code=Configure me!`
3. Use the `ALL` functor doesn't work. See the posts above for a more detailed error message.

**Comment by manuelfs** [comment]
You could try applying one very loose cut for each, eg, `algo_D0.MotherCut = "(ADMASS('D0') < 1000*MeV)`

**Comment by yipengsun** [comment]
That worked. It turns out not all LoKi functors are valid everywhere. But now the reconstruction is very slow (as expected).

**Comment by yipengsun** [comment]
The script crashed after running for ~1 hr. More investigation needed.

**Comment by yipengsun** [comment]
I've pushed the script to branch `run1-unstripped`. No plan to do further debugging, as the segfault involved too many packages.

**Comment by yipengsun** [comment]
Attached is the error message: 
[davinci_segfault.txt](https://github.com/umd-lhcb/lhcb-ntuples-gen/files/4599748/davinci_segfault.txt)

**Comment by yipengsun** [comment]
Now I just remove the momentum-related cuts, and it runs without problems. I think the previous problem was due to some memory leakage: Since we are basically processing every single event in the DST files, eventually all memory gets taken by DaVinci and it crashes.

**Comment by manuelfs** [comment]
Great! Now try to subtract other cuts in order of importance, possibly masses, vertexing, etc. Definitely back off anything that was looser in Run 1 stripping

**Comment by yipengsun** [comment]
For the `ADAMASS` and `ADMASS`, I don't think we need/should remove them, as these are the mass DIFFERENCE between reconstructed particles and PDG reference mass values.

So, the things that can be relaxed are: `M`, `AM`, `M-MAXTREE`.

**Comment by manuelfs** [comment]
I want to see the mass distributions before we cut on them. These ntuples are a one-off, so I want to be able to see as many distributions before cutting on them as possible

**Comment by yipengsun** [comment]
I've removed ALL kinematics-related cuts. @manuelfs Please double-check these scripts before I commit them to GRID.

**Comment by yipengsun** [comment]
I guess once you finish checking, you can close #34.

**Comment by yipengsun** [comment]
I'm copying most of the stripping cuts in a YAML file to basically recreate stripping. I'm not sure if some of the LoKi-functor can be properly translated. For example:
```
MIPCHI2DV(PRIMARY) > 45.0
```

So it's good that we only removed kinematics-related cuts for our _BARE_ ntuples.

**Comment by manuelfs** [comment]
As I wrote in the first post here, I think `MIPCHI2DV(PRIMARY)` → `IPCHI2_OWNPV` in our ntuples. And we may remove cuts on this kind of variable as I said.

**Comment by yipengsun** [comment]
But what about `ACHILD(PT, 1)`? In run 2, Phoebe removed that cut, AFAIK (no `ACHILD` functor in the run 1 `reco_Dst.py`). In run 2, this cut is copied to the reconstruction script.

**Comment by manuelfs** [comment]
You mean, the `ACHILD(PT, 1) + ACHILD(PT, 2) > 2500*MeV` cut? That is just the sums of `pT` of the `K` and `pi`. That is the *main* cut we want to remove from these ntuples

**Comment by yipengsun** [comment]
I don't think `MIPCHI2DV(PRIMARY) → IPCHI2_OWNPV` is valid: I just checked `k_IPCHI2_OWNPV` branch, and the minimum value is `9.10581944777182`. But stripping requires `MIPCHI2DV(PRIMARY) > 45.0`.

**Comment by manuelfs** [comment]
In Run 2 we have a cut at 9
<img width="692" alt="image" src="https://user-images.githubusercontent.com/4977423/82948712-4ae69380-9f70-11ea-9b37-78c43d43598a.png">

In Run 1 we have a cut at 45
<img width="657" alt="image" src="https://user-images.githubusercontent.com/4977423/82948752-62be1780-9f70-11ea-9b26-5d73bdb87881.png">

**Comment by yipengsun** [comment]
Ah, I was looking at run 2 ntuple when comparing with run 1 stripping! My fault indeed.

**Comment by yipengsun** [comment]
The `ADAMASS` definitely doesn't translate into 'MM' branch. Applying the `ADAMASS('D0') < 80.0*MeV` kills all events.

**Comment by yipengsun** [comment]
@manuelfs Even after apply most of the run 1 stripping cuts (The definition can be seen [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/postprocess/Dst-stripping.yml)), the _BARE_ still doesn't agree with regular _cutflow_ ntuple. 

I think this is likely due to the cuts in the `reco_Dst.py` defined differently than the stripping ones.

So I think my immediate next step is synchronize between the two. Do you want me to synchronize to Phoebe's definition or the vanilla stripping? I think I prefer Phoebe's for run 1, and vanilla stripping for run 2.

**Comment by yipengsun** [comment]
I combined stripping cuts and Phoebe's additional cuts. Then I applied the cuts to both regular _cutflow_ and _bare_ ntuple. The generated _bare-step2_ ntuples has twice the events, comparing to _cutflow-step2_.

If I did everything correctly, at least these 2 numbers should be identical. So there must be something wrong, but I haven't been able to figure it out.

**Comment by manuelfs** [comment]
For `ADAMASS`, you should use `MM` indeed, but subtracting the PDG mass. I see that you already are doing [something similar](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/184b079df3e928378c9215bc6a298b6c27a0944f/run1-b2D0MuXB2DMuNuForTauMuLine/postprocess/Dst-stripping.yml#L72) except using `M` instead of `MM`.

We should validate the step 1 ntuples first, without any postprocessing or additional cuts. Just the `CUTFLOW` ntuples as they come out of DaVinci vs the `BARE` ntuples as the come out of DaVinci with the loosened cuts. If they don't agree, you should remove each cut in DaVinci one by one. Meaning, generate a `BARE` ntuple with just one cut different and make sure after cutting on the branch it agrees with `CUTFLOW`. Then, remove another cut in DaVinci, generate a new `BARE` ntuple, and synchonize it with `CUTFLOW` again. And so on.

You seem to be using step 2 ntuples in that `.yml` file, but validating step 2 ntuples should be a separate step to be able to disentangle bugs. Baby steps, Yipeng, baby steps :o)

**Comment by yipengsun** [comment]
The _step2_ is in name only. The postprocess YAML file only includes stripping cuts (+ 1 cut Phoebe tightened), NO trigger NOR real step 2 cut is included.

**Comment by yipengsun** [comment]
I tried to reconstruct _cutflow_ ntuple without stripping filter, and I got 429 events. The regular _cutflow_ ntuple has 430 events.

**Comment by yipengsun** [comment]
The `Dst-stripping.yml` tries to apply only stripping cuts (+ 1 cut Phoebe tightened) to generated _cutflow_ and _bare_ ntuples. 

Ideally, after applying it, the _cutflow_ ntuple should have NO change, and _bare_ ntuple should agree with _cutflow_ ntuple. However, in its current form, the _cutflow_ ntuple has some additional B candidates discarded, while the _bare_ still has too many candidates. This suggests that some of the cuts are TOO tight, and some other cuts are NOT tight enough.

**Comment by yipengsun** [comment]
A brief summary

| mode | # of events | after postprocessing |
|---|---|---|
| _bare_, but with all stripping cuts | 994 | 430 |
| _cutflow_, but use unstripped particles | 993 | 430 |
| _cutflow_, vanilla | 430 | 375 |

**Comment by yipengsun** [comment]
This file contains all the 2012 run 1 stripping: https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/postprocess/Dst-stripping.yml

**Comment by yipengsun** [comment]
I checked the 2011 stripping line, and it turned out that the cuts are identical.

- 2011: http://lhcbdoc.web.cern.ch/lhcbdoc/stripping/config/stripping20r1/semileptonic/strippingb2d0muxb2dmufortaumuline.html
- 2012: http://lhcbdoc.web.cern.ch/lhcbdoc/stripping/config/stripping21/semileptonic/strippingb2d0muxb2dmunufortaumuline.html

I've spotted 3 bugs in my code:

1. The stripping uses `AllLooseMuon`, `LoosePion`, `LooseKaon`
2. The muon cuts was previously not included in the reco script
3. One of the cuts in the reco script has the wrong condition.

I've fixed these 3, but I still get 452 candidates when running _bare_ with all cuts, and 429 candidates when running _cutflow_.

**Comment by yipengsun** [comment]
So I'm either missing cuts, or I'm not using the correct particle location. But haven't been able to identify the remaining bug(s).

**Comment by yipengsun** [comment]
I checked the option file for the cocktail MC, and indeed, the stripping used there was `20r1`, so the cuts are identical with the later 2012 cuts.

I think this has something to do with the momentum smearing (since that's the first step for processing MC, and I think for MC flagging, no momentum smearing is used).

**Comment by yipengsun** [comment]
Disabling momentum smearing, I got 453 reconstructed candidates, so this is not the problem.

**Comment by yipengsun** [comment]
@manuelfs can you help me take a look? Currently the _bare_ specific parts are commented out so all cuts will be applied to _bare_.

What I've checked:

0. Correct particle names used (`StdLooseKaons`, `StdLoosePions`, `StdAllLooseMuons`)
1. Old and new strippings are identical, so no need to have another flag for stripping version
2. All stripping cuts are included and identical (maybe double-check?)
3. D* has some Phoebe-defined cuts. I included them without doing anything else.
4. Phoebe also defined some MC-specific cuts, I also didn't touch them.

BTW, our reconstruction is not exactly as described in stripping line (We reconstruct a D*, but stripping doesn't), so even if we fully copy the stripping line cuts, we may not have the same result.

**Comment by yipengsun** [comment]
To be more precise, the stripping line root decay descriptor is:
```
[ '[B- -> D0 mu-]cc' , '[B+ -> D0 mu+]cc' ]
```

But ours is:
```
'[B~0 -> D*(2010)+ mu-]cc'
```

**Comment by manuelfs** [comment]
I started looking at it and can confirm your findings. I get 453 events with `BARE` and 429 with `CUTFLOW`. I went over the cuts and particle lists, and they indeed seem to match the stripping line.

To debug this kind of thing I typically go to the fastest turnaround time process I can find, and change the minimal number of things. In this case, since there is a difference of 24 events, I can run over 10 times fewer events and expect a difference of ~2.4 events. So instead of running over the 37k events I ran over 4k and found 42 and 39 events, roughly as expected.

Then I did a minimal change. With the `BARE` the moment you use a list from the stripped particles, it goes to 39 events. But that is expected because if there is a stripped Kaon, say, that means the whole event was stripped. So the minimal change is using the `Loose` lists.

Next I looked at the only difference that we could find, and I think that's mostly it. It may indeed be the fact that the stripping applies cuts to the `D0 mu` combination, while in our script we cut on the `D* mu` combination. I added a `Bminus` tree (using [this script](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-b2D0MuXB2DMuNuForTauMuLine/test_reco_Dst_Bminus.py)) with `"[B- -> D0 mu-]cc"` and `CUTFLOW` has 714 events and `BARE` 719.

We should think a bit more on it, but you really are on a good track now. Good job.

**Comment by manuelfs** [comment]
I got a bit closer by applying `nSPDhits < 600` in the ntuple (717 events vs 714, see #41). Of course, `numPVs >= 1` did nothing.  

At this point I think we are close enough to say we understand these cuts and ntuples, although we can check with Phoebe and Svende if they can think of any other source of disagreement. 

You can go ahead now to create the actual `BARE` nuple. Specifically
- Turn momentum smearing back on and focus on the `B0` tree. This will be your nominal `CUTFLOW` ntuple
- Remove `P` and `PT` cuts
- Make all other cuts twice looser that the loosest between Run 1 and 2. For instance,
  - `K_MIPCHI2DV(PRIMARY) > 8`
  - `TRGHOSTPROB < 1`
  - `BPVDIRA > 0.998`
  - `ADAMASS('D0') < 200 *MeV`
If this does not run, you can tighten some of the cuts until it runs. 
- Finally, check that the `BARE` ntuple that you get is the same as the `CUTFLOW` ntuple after you apply the stripping cuts interactively. Post the two ntuple and string of cuts.
- Success!

**Comment by yipengsun** [comment]
With this single cut:
```cpp
b0_ENDVERTEX_CHI2 / b0_ENDVERTEX_NDOF < 6.0
```

The _cutflow_ ntuple has 3 fewer candidates (429 -> 426).

**Comment by yipengsun** [comment]
Now, both run 1 and run 2 _bare_ (cut later) and _dv_stripped_ are in perfect agreement.

**Comment by manuelfs** [comment]
That's excellent! Can you point to the ntuples and cuts? Thanks.

**Comment by yipengsun** [comment]
Finally, jobs submitted. I'll do some cleanups and ask @manuelfs to check the `reco_Dst.py` scripts again. After that, we are pretty much ready to release `0.8.6`.

**Comment by yipengsun** [comment]
Validation info

## run 1

- bare: `lhcb-ntuples-gen/run1-b2D0MuXB2DMuNuForTauMuLine/samples/Dst--20_06_04--cutflow_mc--cocktail--2011--md--dv45-subset-bare.root'
- dv_stripped: `lhcb-ntuples-gen/run1-b2D0MuXB2DMuNuForTauMuLine/samples/Dst--20_06_04--cutflow_mc--cocktail--2011--md--dv45-subset-dv_strip.root`

string of cuts:
```
(mu_IPCHI2_OWNPV > 45.0) && (mu_TRACK_GhostProb < 0.5) && (mu_PIDmu > 2.0) && (mu_P > 3.0*1000) && (mu_TRACK_CHI2NDOF < 3.0) && (k_PIDK > 4.0) && (k_IPCHI2_OWNPV > 45.0) && (k_P > 2.0*1000) && (k_PT > 300.0*1) && (k_TRACK_GhostProb < 0.5) && (pi_P > 2.0*1000) && (pi_PT > 300.0*1) && (pi_IPCHI2_OWNPV > 45.0) && (pi_PIDK < 2.0) && (pi_TRACK_GhostProb < 0.5) && (spi_IPCHI2_OWNPV > 0.0) && (spi_TRACK_CHI2NDOF < 3.0) && (spi_TRACK_GhostProb < 0.25) && (k_PT + pi_PT > 1400.0*1) && (abs(d0_MM - 1864.83) < 80.0*1) && (d0_ENDVERTEX_CHI2 / d0_ENDVERTEX_NDOF < 4.0) && (d0_FDCHI2_OWNPV > 250.0) && (d0_DIRA_OWNPV > 0.9998) && (abs(dst_MM - 2010.26) < 125.0*1) && (dst_M - d0_M < 160.0*1) && (dst_ENDVERTEX_CHI2 / dst_ENDVERTEX_NDOF < 100.0) && (0.0*1000 < b0_MM < 10.0*1000) && (b0_ENDVERTEX_CHI2 / b0_ENDVERTEX_NDOF < 6.0) && (b0_DIRA_OWNPV > 0.9995)
```

The dv_strip contains 452 candidates, after applying the cuts, the bare has 452 candidates remaining.

**Comment by manuelfs** [comment]
Great job!
