### ISSUE TITLE
Synchronizing stripping and DaVinci cuts

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#41]
Yipeng and I prepared [this script](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/ba2246d1c2cf521690ea354ce1c8b3c845c4ebf9/run1-b2D0MuXB2DMuNuForTauMuLine/test_reco_Dst_Bminus.py) to try to sync the cuts in the DaVinci script to those in the stripping line. Depending on the flag, it produces a `CUTFLOW` ntuple using the stripped particles and filter, or a `BARE` ntuple with identical cuts but no stripping. Specifically, we
- Turned off momentum smearing
- Used the `Loose` particle lists for mu, K, and pi
- Copied cuts from [stripping line in `20r1`](http://lhcbdoc.web.cern.ch/lhcbdoc/stripping/config/stripping20r1/semileptonic/strippingb2d0muxb2dmufortaumuline.html)
- Constructed a `B- -> D0 mu-` decay in the `Bminus` tree
- Applied offline the `nSPDhits<600` cut

After doing all this and running on 37k cocktail 2011 events, the `CUTFLOW` ntuple has 714 events while the `BARE` ntuple has 717. Why, oh, why?

**Comment by yipengsun** [comment]
Actually, I think applying cuts on the B0 (-> D*mu) with stripping line cuts doesn't make too much sense, maybe we should go back to Phoebe's original cuts for B0 only?

Note that there was no cut defined for D*, and we just keep using Phoebe's.

**Comment by manuelfs** [comment]
Of course we go back to B0 only. The Bminus was just to check that we were doing the right thing.

**Comment by yipengsun** [comment]
BTW, the difference of 3 reconstructed candidates is still weird, but I think as you said, we have enough, though not perfect, understanding of this and we can just proceed.

For a moment I was thinking that maybe you did some re-fitting on the B- as well, but I was wrong:

1. You DID NOT do any refitting
2. Refitting won't change `nSPDhits`

So this is an unsolved mystery, but I'm going to move forward nonetheless.

**Comment by manuelfs** [comment]
A related question that I asked in Slack is, given that the stripping line has cuts on the `D0 μ` combination, but in the D* sample no `D0 μ` combination is built, how does one apply the stripping cuts to unflagged MC? Should they be applied to a spurious `D0 μ` combination?

**Comment by yipengsun** [comment]
I mean, the D0 μ cuts were applied to B0, even though we are missing particles:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/54b093219868fab45e88265bb3378e82d621872f/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst.py#L333-L347

The snippet above is from `0.8.5`. So Phoebe was just applying the cuts of the D0 μ combo to B0.

BTW, in the LHCb stripping doc, the D0 μ combo is referred as "b" (Can't access the stripping webpage right now, need double-checking).

**Comment by yipengsun** [comment]
Well, Phoebe was not applying any cut on μ.

**Comment by manuelfs** [comment]
Exactly, if the cuts are applied to the `D* mu` combination there would be a slight misalignment between unflagged MC and data. So I asked he is she just accepted it, or did something else. I'm pretty sure it is not a big deal, but was curious.

**Comment by yipengsun** [comment]
She just accepted the cuts on the combo, but ignored the cuts on the Muon.

**Comment by yipengsun** [comment]
Well, for some reason, I just can't open the stripping line webpage. I can access CERN website though, so I think there might be some technical problems with the stripping website?

**Comment by manuelfs** [comment]
I can access the stripping line http://lhcbdoc.web.cern.ch/lhcbdoc/stripping/config/stripping20r1/semileptonic/strippingb2d0muxb2dmufortaumuline.html. What do you need it for anymore? We should have all the relevant cuts by now.

By the way, I think some of this conversation may be better kept to Slack (various people may receive notifications from these comments that do not contribute much to the issue at hand).

**Comment by manuelfs** [comment]
We still do not know where the difference between the stripped ntuple with 714 events and the `BARE` (now `DV_STRIPPED`) with 717 events come from, but for now we are moving on.
