### ISSUE TITLE
Multiplicity of the cutflow bare ntuples

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#42]
Previous I was always operating under the assumption that:
> For most of the candidates,  UIDs, defined as `runNumber` + `eventNumber` (string concatenation, NOT arithmetic addition), are unique

However, for our _bare_ ntuples, most of the candidates have duplicated UIDs:
```
> uiddump -n Dst--20_06_05--cutflow_mc--bare--MC_2011_Beam3500GeV-2011-MagDown-Nu2-Pythia8_Sim08h_Digi13_Trig0x40760037_Reco14c_Stripping20r1NoPrescalingFlagged_11874091_ALLSTREAMS.DST.root  -t TupleB0/DecayTree
Total: 233735, duplicate: 225955, duplicate rate: 96.67144415684429%

> uiddump -n ./Dst--20_06_05--cutflow_mc--bare--MC_2016_Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8_Sim09b_Trig0x6138160F_Reco16_Turbo03_Stripping26NoPrescalingFlagged_11874091_ALLSTREAMS.DST.root -t TupleB0/DecayTree
Total: 334697, duplicate: 328687, duplicate rate: 98.20434602043042%
```

Now, when looking at 2012 _bare_:
![eventNumber](https://user-images.githubusercontent.com/33738176/84465548-e0409200-aca9-11ea-8b8b-c5f9baa2535b.png)
![runNumber](https://user-images.githubusercontent.com/33738176/84465555-e3d41900-aca9-11ea-9cfe-43b681a1f6de.png)

According to the DaVinci log, the total number of **EVENTS** after reconstruction is 77426 for **RUN 1**. We have 233735 candidates for run 1, so already we have a multiplicity of 3 (on average, every 3 candidates have the same UID).

@manuelfs I'm not familiar with this problem. My assumption is that the reconstruction went OK, but the UID is no longer meaningful for massive MC ntuples without most of the cuts?

Then the question is, how do we generate a sane cutflow? i.e. the jump from `SelMyB0` to number of candidates is ill-defined (77426 -> 233735, the efficiency is greater than 1).

**Comment by yipengsun** [comment]
I can certainly do a more thorough UID check: For candidates with the same UID, do their kinematics agree?

**Comment by yipengsun** [comment]
I double checked the input data files to the GRID jobs. They seem fine: No duplicated dst file used for the GRID jobs.

**Comment by yipengsun** [comment]
I can confirm that the high multiplicity is not a bug introduced by me. I downloaded a _unmerged bare_ ntuple straight from the Ganga job output:

```
> uiddump -n cutflow_mc-bare.root  -t TupleB0/DecayTree
Total: 10497, duplicate: 10101, duplicate rate: 96.22749356959132%
```

**Comment by manuelfs** [comment]
We do expect to have many candidates per event before applying tight cuts on vertexing and others. There are many particles in each event, so you can build many, many `D0 -> K pi` candidates if you are not tight enough.

It does raise questions on how to do the cutflow so that it is meaningful. One possibility is to do the entire cutflow on a per event basis (counting the number of unique events). If you do the counting for all the rows in one go it should not be too slow. You can also have a separate cutflow with candidates, as I'm curious to know which cuts reduce the average number of candidates per events.

**Comment by yipengsun** [comment]
It is weird to me that out of the ~500,000 events, all of the reconstructed candidates come from ~7800 events.

Also, I think if we want to do cutflow from the beginning, the in this case the only consistent way is to **do it on a per-event basis**.

The problem with **per-candidate** basis is that we can't figure out **number of candidates** from the DaVinci log.

**Comment by yipengsun** [comment]
Anyway, I think given the unique problem of the _bare_, I'd like to hear some of Phoebe's inputs.

Here's my summary on the current question:

We finished reconstructing B0 -> D* l nu candidates **WITHOUT most of the stripping cuts (e.g. We removed kinematics cuts and some of the vertex quality cuts). Let's denote these candidates as _bare_.

An unique feature (or bug maybe) of the _bare_: In the _bare_ for 2012 MagDown (cocktail MC), I have ~233,000 candidates, but most of the candidates have the same UID, defined as the string concatenation of the `runNumber` + `eventNumber`.

Note that total number of events in the cocktail MC is ~500,000, and out of the reconstructed ~233,000 candidates, there are only ~7,800 UIDs. This is very different from all previous cases, where most of the candidates have truly unique UIDs.

Naively I'd expect that with very loose cuts, we can reconstruct a B0 candidate from basically every event?

**Comment by yipengsun** [comment]
Here's the currently incorrect event-based cutflow:

| cut name                                      | run 1 yield   | run 2 yield   | run 1 efficiency       | run 2 efficiency       | double ratio           |
|-----------------------------------------------|---------------|---------------|------------------------|------------------------|------------------------|
| Total events                                  | 502736        | 520046        | -                      | -                      | -                      |
| $D^0 \rightarrow K^- \pi^+$ (tighter $K \pi$) | 89441         | 94498         | 0.18680±0.00056        | 0.19328±0.00056        | 1.0347±0.0043          |
| $D^{*+} \rightarrow D^0 \pi^+$                | 89277         | 94412         | 0.99817±0.00015        | 0.99909±0.00011        | 1.00093±0.00019        |
| $\bar{B}^0 \rightarrow D^{*+} \mu^-$          | 47858         | 51329         | 0.6181±0.0017          | 0.6082±0.0017          | 0.9840±0.0039          |
| L0                                            | 18742         | 16392         | 0.3916±0.0022          | 0.3194±0.0021          | 0.8155±0.0070          |
| Hlt1                                          | 9201          | 16383         | 0.4909±0.0037          | 0.99945±0.00025        | 2.036±0.015            |
| Hlt2                                          | 3761          | 8232          | 0.4088±0.0052          | 0.5025±0.0039          | 1.229±0.018            |
| Stripping                                     | 6144          | 13839         | 1.6336080829566604±nan | 1.6811224489795917±nan | 1.0290855355814201±nan |
| $\mu$ PID                                     | 5786          | 12213         | 0.9417±0.0031          | 0.8825±0.0028          | 0.9371±0.0043          |
| $\text{IsoBDT}_{\Upsilon(\text{4s})} < 0.15$  | 4218          | 8624          | 0.7290±0.0059          | 0.7061±0.0042          | 0.9686±0.0097          |
| $m_{\Upsilon(\text{4s})} < 5280$              | 4218          | 8619          | 1.00000±0.00043        | 0.99942±0.00039        | 0.99942±0.00058        |
| Total ratio                                   | -             | -             | 0.00839±0.00013        | 0.01657±0.00018        | 1.975±0.037            |

Something's not right on the trigger part, still investigating.

**Comment by yipengsun** [comment]
I did a validation on my cutflow generation. After re-applying the trigger and stripping cuts:

- In the cutflow generation script, I have 1303 and 4168 **EVENTS**
- Applying the same cuts with `babymaker`, I have 1303 and 4168 **EVENTS**

Since both numbers agree, I think the cutflow generation is bug-free.
