### ISSUE TITLE
Running BARE cutflow

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#43]
I am trying to become familiar with Yipeng's nice and possibly preferable code, so I tried running the `BARE`cutflow. There is no full documentation, so I made up some steps and have some questions at the bottom of the issue.

I first uninstalled my installations of old python modules, and added the new submodules to `lhcb-ntuples-gen`
```
pip3 uninstall pyTuplingUtils
pip3 uninstall pyBabyMaker
git submodule init
git submodule update
```

This cloned the appropriate commits in `lib/python`, but did not install them. So I just went ahead and installed them manually
```
cd lib/pythong/pyTuplingUtils
python3 setup.py build
python3 setup.py install
cd -
```

After this, running the cutflow still complained about several packages like `uproot` that I had already installed. This was because it was using python 2. So I decided to install `pyenv` as Yipeng had recommended
```
brew install pyenv
pyenv install 3.8.3
pyenv global 3.8.3
pyenv version
echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
```

This changed indeed my `python` and `pip` commands to python 3.8.3., but since I had python 3.7.3 before, I had to reinstall all my packages
```
pip install --user -r requirements.txt
cd lib/pythong/pyTuplingUtils
python3 setup.py build
python3 setup.py install
cd -
```

After all this the standard cutflow worked!
``` 
make cutflow-Dst
```

The `BARE` cutflow however complains about missing ntuples
```
|16:52:11|~/code/lhcb-ntuples-gen$ make cutflow-Dst-bare
make: *** No rule to make target `Dst--20_06_05--cutflow_mc--bare--MC_2011_Beam3500GeV-2011-MagDown-Nu2-Pythia8_Sim08h_Digi13_Trig0x40760037_Reco14c_Stripping20r1NoPrescalingFlagged_11874091_ALLSTREAMS.DST.root', needed by `gen/cutflow/output-run1-bare.yml'.  Stop.
```

These error messages are not very useful because they don't tell you where these ntuples are expected to be. When I found them I tried to `annex get` them to no avail
```
|17:02:35|~/code/lhcb-ntuples-gen/ntuples/0.9.0-cutflow/Dst-cutflow_mc$ git annex get Dst--20_06_05--cutflow_mc--bare--MC_2011_Beam3500GeV-2011-MagDown-Nu2-Pythia8_Sim08h_Digi13_Trig0x40760037_Reco14c_Stripping20r1NoPrescalingFlagged_11874091_ALLSTREAMS.DST.root 
get Dst--20_06_05--cutflow_mc--bare--MC_2011_Beam3500GeV-2011-MagDown-Nu2-Pythia8_Sim08h_Digi13_Trig0x40760037_Reco14c_Stripping20r1NoPrescalingFlagged_11874091_ALLSTREAMS.DST.root (not available) 
  No other repository is known to contain the file.


  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 1 failed
```

I tried `git annex sync julian` but no ntuples were found (and may have made a commit to `lhcb-ntuples-gen` that I had to delete). 

My questions for Yipeng
- Are the `BARE` ntuples not copied to `julian`?
- Where in `julian` are all the ntuples? `data/lhcb-ntuples-archive` is very old, and we need to be able to browse all the available ntuples, see their sizes, quickly look at them interactively, etc.
- How are the submodules in `lhcb-ntuples-gen` actually installed? Does one have to redo the installation after you pull a new commit of `lhcb-ntuples-gen` that has new commits of the modules?

Thanks!

**Comment by yipengsun** [comment]
To answer you questions:

1. Yes, I forgot to copy the newly-generated ntuples to `julian`.
2. The annexed files are stored in a git repository, which is not transparent to us.

    To see a list of annexed files and their availability, use
    ```
    git annex list .
    ```

    To see the file size:
    ```
    git annex info <path_to_annexed_file>
    ```
3. The submodules need to be initiated: 
    ```
    git submodule update --init --recursive
    ```
    Then go back to project root, and run `make install-dep`.

    And yes, you have to redo `make install-dep` if you update something in the submodules or if some remote change has occurred regarding the submodules.

**Comment by yipengsun** [comment]
We probably should add the above `git annex` commands to our wiki. If you have time, can you try these commands and add them to the `git-annex` page (located in [`docs/software_manuals/git_annex.md`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/docs/software_manuals/git_annex.md))

**Comment by yipengsun** [comment]
Also, I see that you changed the shabang from `/usr/bin/env python` to `/usr/bin/env python3`, which is fine. But with a `pyenv` setup, that change will not be needed (though change to `python3` will not break anything for now).

**Comment by yipengsun** [comment]
I've included a short guide on how to install and use `pyenv` for this project.

**Comment by manuelfs** [comment]
Thank you Yipeng for the responses here and in our little meeting! For reference, this is what I learned
- The shebang with `python3` is indeed not needed after I installed `pyenv`. It was just that `git annex sync julian` commits and pushes to GitHub if your working directory is not clean...
- `git submodule update --init --recursive` can be run from anywhere in the `lhcb-ntuples-gen` (not inside the actual submodules), but `make install-dep` has to be in the project root because of the `Makefile`
  - If the links to the submodules commits change after a `git pull`, you need to run `git submodule update` and then `make install-dep`
  - To do development in a submodule such as `pyTuplingUtils`, a good way is to modify directly the code in `lhcb-ntuples-gen/lib/python/pyTuplingUtils` and commit it there. One may require a `git pull` inside there to make sure you're in the lastest commit, and check that it still is compatible with `lhcb-ntuples-gen`

There is a number of things that need updating in the wiki, but I take note the `git annex list .` and `git annex info <path_to_annexed_file>` commands. Very helpful!

By the way, I also parsed the `Makefile` and this
```
gen/cutflow/output-run1.yml: \
    Dst--20_03_18--cutflow_mc--cocktail--2011--md.root \
    input-run1.yml \
    cutflow_output_yml_gen-pre-0.9.0.py
    @$(word 3, $^) $< $(word 2, $^) $@ run1 -t 'TupleB0/DecayTree'

gen/cutflow/output-run2.yml: \
    Dst--20_03_18--cutflow_mc--cocktail--2016--md.root \
    input-run2.yml \
    cutflow_output_yml_gen-pre-0.9.0.py
    @$(word 3, $^) $< $(word 2, $^) $@ run2 -t 'TupleB0/DecayTree'

cutflow-Dst: \
    gen/cutflow/output-run1.yml \
    gen/cutflow/output-run2.yml
    @cutflow_gen.py -o $< -t $(word 2, $^) -n | tabgen.py -f latex_booktabs_raw
```
simply translates to
```
utils/cutflow_output_yml_gen-pre-0.9.0.py ntuples/pre-0.9.0/Dst-cutflow_mc/Dst--20_03_18--cutflow_mc--cocktail--2011--md.root run1-b2D0MuXB2DMuNuForTauMuLine/cutflow/input-run1.yml gen/cutflow/output-run1.yml run1 -t 'TupleB0/DecayTree'
utils/cutflow_output_yml_gen-pre-0.9.0.py ntuples/pre-0.9.0/Dst-cutflow_mc/Dst--20_03_18--cutflow_mc--cocktail--2016--md.root run2-b2D0MuXB2DMuForTauMuLine/cutflow/input-run2.yml gen/cutflow/output-run2.yml run2 -t 'TupleB0/DecayTree'
utils/cutflow_gen.py -o gen/cutflow/output-run1.yml -t gen/cutflow/output-run2.yml -n | tabgen.py -f latex_booktabs_raw
```
