### ISSUE TITLE
Script to list sizes of ntuple folders in git annex

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#46]
We need a script that will tell us the size of the folders that contain the ntuples stored in the git annex before they are downloaded to our computer. Output should look like something like this script's https://github.com/manuelfs/babymaker/blob/master/bmaker/genfiles/python/count_root_files.py

![image](https://user-images.githubusercontent.com/4977423/87536605-59475680-c667-11ea-950c-91269836721e.png)

It may be useful to be able to list the ntuple files themselves and their sizes as an option.

**Comment by yipengsun** [comment]
I think `git annex info` is mostly what we want, but we can have nicer output. I can write a wrapper real quick.

**Comment by yipengsun** [comment]
I've made a wrapper script called [`scripts/count_root_files`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/scripts/count_root_files.py).

I've also updated the [`git-annex` documentation](https://umd-lhcb.github.io/lhcb-ntuples-gen/software_manuals/git_annex/#check-annexed-file-size) to reflect this change.
