### ISSUE TITLE
Check of wrong-sign samples reconstruction

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#48]
In the current version of [`reco_Dst_D0.py`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/d0/run1-b2D0MuXB2DMuNuForTauMuLine/reco_Dst_D0.py#L1), Yipeng reconstructs three wrong-sign trees
- `B+  → D0 (K- pi+) mu+ (Bminus_ws)`
- `B~0 → D*+ (D0 → (K- pi+) pi+) mu+ (B0_ws_Mu)`
- `B~0 → D*- (D0 → (K- pi+) pi-) mu- (B0_ws_Pi)`

The first is the wrong-sign muon for the `D0mu` sample, the second the wrong-sign muon for the `D*+mu` sample, and the third the wrong-sign pion which gives combinatorial `D*+` mesons in the `D*+mu` sample. They all look correct to me. This is how Phoebe defined the wrong-sign samples for the `D*+mu` sample in the [Run 1 ANA note](https://github.com/umd-lhcb/group-talks/blob/master/ana_thesis/LHCb-ANA-2014-052_Run1_RDs.pdf)
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/4977423/89487599-e7e55a00-d773-11ea-8a88-ecb9a39c3b6f.png">

For reference, the correct-sign trees are
- `D0  → K- pi+` (`D~0 → K+ pi-`)
- `D*+ → D0 pi+` (`D*- → D~0 pi-`)
- `D*0 → D0 pi/gamma` 
- `B0  → D*- mu+ nu`
- `B-  → D0 mu- nu`
- `B-  → D*0 mu- nu`

**Comment by yipengsun** [comment]
Also, as we discussed in Tuesday's meeting, you should also check the `RequiredSelections` of the wrong-sign selections to make sure my logic is correct.

For example, the B0 -> D* Mu, wrong-sign Mu uses:
```
sel_D0_ws_combo
pr_all_loose_Pi
sel_Mu_ws_combo
```

as inputs, and you should see if you agree with my choice of input.

**Comment by manuelfs** [comment]
Checked the inputs to the three wrong sign trees, and I think they are correct (and it was not easy, good job Yipeng!). 

There are some inputs that are only used to apply the stripping cuts such as `sel_Dst_ws_Mu` and `sel_Mu_ws_combo`. Since wrong-sign trees only make sense in data, which is always stripped, these inputs are redundant and could be removed to clean up the code, but it is fine if they stay.

Specifically, I checked the `TupleBminusWS` inputs
- `sel_Bminus_ws`
- `sel_refit_Bminus2D0Mu_ws`
- `seq_Bminus_ws`

Checked the `TupleB0WSMu` inputs
- `sel_Bminus_ws`
- `sel_Dst_ws_Mu`
- `sel_Mu_ws_combo`: 
- `sel_B0_ws_Mu`
- `sel_refit_B02DstMu_ws_Mu`
- `seq_B0_ws_Mu`

Checked the `TupleB0WSPi` inputs
- `sel_Dst_ws_Pi`: 
- `sel_B0_ws_Pi`
- `sel_refit_B02DstMu_ws_Pi`
- `seq_B0_ws_Pi`
