### ISSUE TITLE
Further validation for step-2 cuts with 2011 real data

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#50]
As discussed in today's meetings, there's no need to replicate Phoebe's `proc/AddB.c` for now.

However, since Phoebe has many `if`'s, the same variable likely have different meanings for different types of sample (e.g. data or MC or control sample).

I'll document the skeleton of the `if`'s here.

The comments are based on [this version of `AddB.c`](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/f78365bfc3000ef70ced2ed271ec42aa866c44af/proc/AddB.C).

## Variables to check

One should first check vectorized logical operation functions defined in [`basic.h`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/include/functor/basic.h).

The original variables are defined in [this version of `AddB.c`](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/f78365bfc3000ef70ced2ed271ec42aa866c44af/proc/AddB.C).

### Selecting components
Unless specified, all variables are defined in [`flag.h`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/include/functor/flag.h).

Functions that need checking have comments of this form:
```cpp
// Original name: muPID
// Current name: mu_pid
// Meaning: Real muon or not
// Defined in: AddB.C, LN2500, LN2540
Bool_t MU_PID( ... )  // <--- Note the functions are all UPPER case to avoid name conflicts with real variables.
```

#### PID
- [x] `mu_pid` (in [`pid.h`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/include/functor/pid.h))
- [x] `dst_id_prod` (in [`rdx-run2-mc.yml`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/postprocess/rdx-run2/rdx-run2-mc.yml))
- [x] `id_prod` (in [`rdx-run2-mc.yml`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/postprocess/rdx-run2/rdx-run2-mc.yml))

#### Physical variables
- [x] `mm_dst_mom` (in [`kinematic.h`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/include/functor/kinematic.h))
- [x] `b0_bkg_cat` (in [`rdx-run2-mc.yml`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/postprocess/rdx-run2/rdx-run2-mc.yml), simple renaming)

#### Flags
- [x] `flag_tau`
- [x] `flat_mu`
- [x] `flag_two_d_tau`
- [x] `flag_two_d_mu`
- [x] `flag_d0_mu`
- [x] `flag_dst_sb`: Flag for D* side-bands. Obsolete.

#### Other flags
- [x] `is_data`
- [x] `is_2pi`
- [x] `just_dst`
- [x] `dst_ok`

#### Types
- [x] `b_type`
- [x] `dss_type`

## Selections to check

Actual selections are defined in [`include/functor/flag.h`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/include/functor/flag.h).

1. Extracting 2011 MagDown data from Phoebe's step2
    - Selections are defined in [`rdst-2011-mix.yml`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/postprocess/ref-rdx-run1/rdst-2011-mix.yml)
    - Apply pseudo-random sequence to Phoebe's step2 as well, because there's still duplicated B candidates
    - If we don't apply `mu_bdt` cut, 81783 candidates, with no duplicate

2. Apply step2 cuts to Phoebe's 2011 MagDown step1.
    - Selections are defined in [`rdst-2011-data.yml`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/postprocess/ref-rdx-run1/rdst-2011-data.yml)
    - Applied pseudo-random sequence selection to keep only 1 B candidate for multi-B events
    - 81116 B candidates, with no duplicate
    - Do not have `mu_bdt` branch yet

I've also checked the B candidates in both ntuples that have common `runNumber+eventNumber`, there are 81065 of them.

**Comment by yipengsun** [comment]
Note that all processing are done in `void AddB::Process(Long64_t entry)`.

Also, to search for a variable in `vim`, one should use:
```
/some_var_name\s\?=\s\?
```

**Comment by yipengsun** [comment]
## `if(entry==0)`
Things to do for the first entry. Nothing too important.

## `if(counter/increment > current || counter==1 || counter==nentries-1)`
Print out progress bar. Nothing too important.

## `if(lastEvt!=eventNumber)`
Keep only 1 candidate for multi-candidate events, with a PRS derived from ntuple (last few digits of B meson PT).
- `lastEvt`

**Comment by yipengsun** [comment]
Questions so far:

1. For `Btype`: Not sure about the `if (...)` starting at `LN2779`.
2. For `FlagDstSB`: Seems always to be false

**Comment by yipengsun** [comment]
@afernez I've listed variables to check in the top comment of this issue. Could you finish checking the **Selecting components** by mid-Oct?

**Comment by yipengsun** [comment]
`AddB.C` doesn't contain cuts listed in the ANA note. I've browsed through the whole `::Process()` method.

I did find one additional cuts for data (`LN4788`):
```cpp
    if((DstIDprod > 0 && IDprod > 0 && muPID > 0. && flagDstSB==0.) && isData > 0. /*&& flagGhost < 1. && DstOk > 0.*/) 
```

**Comment by yipengsun** [comment]
I'm very confused about `selcounter` in the `AddB.C`. This seems to be the variable that defines various event types (e.g. data, 1OS, etc.), but I don't see it used in `redoHisto.C`.

**Comment by manuelfs** [comment]
The cuts for the samples (ISO, 1OS, etc) are the ones @afernez found and do not depend on `selcounter`. I believe that `selcounter` is the variable Phoebe uses to apply the step 1 cuts in `AddB.C`. The actual cut is at https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/f78365bfc3000ef70ced2ed271ec42aa866c44af/proc/AddB.C#L2694-L2698

She stores each cut as one bit, and then cuts the event away if `selcounter` is not all ones.

She also stores it as a branch, but it was probably for debugging.

**Comment by yipengsun** [comment]
I've tried to implement all step-2 cuts for the 2011 data. Still I have a relatively large discrepancy between 1) extracting 2011 MagDown data from Phoebe's step2 and 2) Apply step2 cuts to Phoebe's 2011 MagDown step1.

I have: 77076 candidates from 1) and 86161 candidates from 2). One unexpected thing from 1) is that I still have candidates with identical `runNumber+eventNumber` (286 of them).

One known missing variable in 2) is the `mu_bdt` (uboost BDT PID for Muon).

**Comment by yipengsun** [comment]
If I remove `mu_bdt` cut from 1), I get 82122 candidates.

**Comment by yipengsun** [comment]
@manuelfs I've checked `selcounter` in `AddB.C`, and added 2 missing cuts. I noticed that `AddB.C` is not fully consistent with ANA.

Now, I have 81783 B cands from Phoebe's step2, and 81116 from applying cuts I found to Phoebe's step2. See top post for more details.

I plan to ask Alex to double check my cuts again, but I don't think there's a lot to do. I think the discrepancy is small enough to overlook, what's your opinion on this?

**Comment by manuelfs** [comment]
Can you be explicit about "I noticed that AddB.C is not fully consistent with ANA."?

**Comment by yipengsun** [comment]
Two inconsistencies:

1. `b0_endvtx_chi2` cut:
    - ANA: `b0_endvtx_chi2/b0_endvtx_ndof < 6`
    - `AddB.C`: `b0_endvtx_chi2 < 24`

2. K, Pi PT cuts:
    - ANA: `k_pt > 0.8 && pi_pt > 0.8 && ((k_hlt1ta_tos && k_pt > 1.7) || (pi_hlt1ta_tos && pi_pt > 1.7))`
    - `AddB.C`: `k_pt > 0.5 && pi_pt > 0.5 && k_pt+pi_pt > 1.4 && (k_hlt1ta_tos || pi_hlt1ta_tos)`

**Comment by manuelfs** [comment]
Ah, thank you. But that is not inconsistent, just looser. The AddB cuts do not have to all the cuts in the ANA note, just a subset. Are those applied in step 2?

In any case, it discrepancy above is indeed small enough to overlook. Nice job!

**Comment by yipengsun** [comment]
Just a quick thought: When constructing `mu_pid` variable, Phoebe seemed to be not using same method for both data and MC.

This is just a quick memory dump from my brain, and I can be wrong.

**Comment by yipengsun** [comment]
Here's a quick and naive comparison between extracting ISO sample from Phoebe's step-2 and applying step-2 cuts on our newly-generated 2011 MagDown ntuple: https://umd-lhcb.github.io/lhcb-ntuples-gen/data/comparison/RDst_step2_cuts_validation/RDst_step2_cuts_validation

In short: **NOT** looking good. Given that I've validated the following case: Applying step-2 cuts to Phoebe's step-1 ntuple yields very similar result to extracting ISO from Phoebe's step-2, I'll take a closer look at how I'm applying step-2 cuts to our newly-generated ntuple (after finish the HAMMER study, of course).

**Comment by yipengsun** [comment]
@manuelfs I've updated links to postprocessing files that are responsible to step-2 cuts to the same comparison documentation.

Again, the link is: https://umd-lhcb.github.io/lhcb-ntuples-gen/data/comparison/RDst_step2_cuts_validation/RDst_step2_cuts_validation

**Comment by afernez** [comment]
@yipengsun Sorry I've taken a while to do this task, but I've gone through and checked **Selecting components**, and here are my notes:
1. I think your definition of `flag_d0_mu` is wrong at your line 145 in `flag.h` since, based on your 2d list `mc_flags` definitions, Phoebe has the equivalent of `mc_flags[0][0] || mc_flags[0][1]` at line 2740 in `AddB.C` (ie. you should replace the 2 with a 1)
2. For `flag_two_d_mu`, I think you’ve ignored Phoebe’s line 4362 in `AddB.C`; I’m not sure if this is purposeful.
3. For `is_2pi`, as you note in a `FIXME`, `CocktailHigher` isn’t defined anywhere… not sure what to do about this. Also, just a note about your comment on your line 271 in `flag.h`: `is_2pi` is defined in Phoebe’s `AddB.C` lines 3255-3269
4. For `just_dst`, you added the conditional at line 2757 of `AddB.C` (in your `flag.h` this is lines 300, 301), but I don’t think this conditional applies to `just_dst`; the bracketing is a little confusing, but I think the only conditional Phoebe is applying is her line 2814 (in `flag.h`, this line is 302).
5. For `b_type`, I think you should move `else b_type=-1` at line 364-365 in `flag.h` inside the bracket (ie. apply the `!flag_d0_mu` conditional), according to Phoebe’s block of code 2841-2866 in `AddB.C`

**Comment by yipengsun** [comment]
@afernez Here's my reply to your comments:

1. Absolutely right. Fixed.
2. I think in my `LN131-132`, we already required that the `abs(mu_id)` is one of the following: `411, 421, 431`, so Phoebe's `LN4362` is implicitly taken into acount
3. Fixed the wrong line numbers in the comment
4. Yeah I think this is correct. Fixed
5. Here I think there are two places where `Btype = -1` in Phoebe's code: `LN2836, LN2862`, so I think it is handled correctly.

**Comment by yipengsun** [comment]
Job for **std reconstruction on 2016 MagDown real data** submitted to the GRID.

**Comment by afernez** [comment]
For my followup check (sorry that it's such a long response for 2):

2. I'm still unsure if this line in Phoebe's code could make her implementation slightly different from yours. Actually, I'm a little confused why her [line 2754](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/f78365bfc3000ef70ced2ed271ec42aa866c44af/proc/AddB.C#L2754) is there at all; I believe it's selecting B->D\*D\*\*X events, where D\*\*=D_s1+, D'_s1+ (20433, 10433) goes to D\*, which goes to D, which goes to mu (but also potentially D\*\*->D->tau->mu? I think this is another possible decay chain where mu's grand-grand-mother is 20433 or 10433, and I think this is the only other possibility? I could be wrong...). But, looking at the table in the ANA note pg 103 ([most recent version](https://github.com/umd-lhcb/group-talks/blob/master/ana_thesis/RD_RDst_ANA_21-01-05.pdf)), I wouldn't have expected `flagDoubleD` to include these events (which don't show up in the table). For the sake of argument, assuming line 2754 isn't meant to be commented out: say it is true, but mu's mother _isn't_ D_q (411,421,431 for q=d,u,s)- then if the conditional on [line 4343](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/f78365bfc3000ef70ced2ed271ec42aa866c44af/proc/AddB.C#L4343) (all of these conditionals seem to be applied together whenever `flagDoubleD` is invoked) is true, Phoebe ends up re-setting `flagDoubleD` to 0, while your function would have already returned true. The only saving grace would be: if it's always going to be true that D\*\*->D\*->D, then requiring that mu's grand-grand-mother be 20433,10433 in line 2754 is the same as requiring its mother be D_q, so in fact this condition is applied there (implicitly) already, and every time Phoebe's line 2754 is true, `flagDoubleD` will not be reset to 0 at line 4362 (effectively, like you say, this line does nothing). If this assumption that we always have D\*\*->D\*->D is true, then I agree your code will work the same as Phoebe's. However, if it isn't, there are cases where they behave differently (effectively, Phoebe adds on a requirement that mu's mother _always_ must be D_q at line 4362, meaning that she's not including events like D\*\*->D->tau->mu for `flagDoubleD`, whereas your code will include them).
5. I thought [your claim in the comment for b_type](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/d4e5ae295a910dc7bbb15335a3909c159633f366/include/functor/flag.h#L319) meant that Phoebe's [line 2836](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/f78365bfc3000ef70ced2ed271ec42aa866c44af/proc/AddB.C#L2836) was obsolete?

**Comment by afernez** [comment]
I edited my comment above. I should have referenced [Manuel's presentation to us](https://github.com/umd-lhcb/group-talks/blob/master/rdx/20-08-11_manuelf_Dss.pdf) about the D\*\* states before submitting the comment. On slide 3, it explains 20433, 10433 (D_s1+, D'_s1+) cannot decay directly to D, they have to decay to D\* first.
