### ISSUE TITLE
Apply MC form factor reweighting with HAMMER

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#51]
We don't have run 2 MC yet, so I'll try to work with run 1 MC first. 

0. The HAMMER manual is available [here](https://www-theory.lbl.gov/~papucci/hammer-tutorial/HammerManual.pdf)
1. Zishuo has put his HAMMER reweighting code up [on github](https://github.com/ZishuoYang/my-hammer-reweighting)
2. ~~Manchester people has an arxiv post about HAMMER: [arxiv](https://arxiv.org/pdf/2007.12605.pdf)~~ This discusses an interface between `HistFactory` and HAMMER, and is not about reweighting
3. We need to update DaVinci scripts to include neutrinos in the decay descriptor.

**Comment by yipengsun** [comment]
According to HAMMER manual:

> In  general,  histogramming  of  event  weights  does  not  commute  with  contraction  of  FF parametrization and weight tensors (unless one of the histogram dimensions is explicitly q2).

I don't understand what is the meaning of this sentence.

**Comment by yipengsun** [comment]
Zishuo's example C++ file can be built with:
```
gcc -pthread -std=c++14 -m64 Bc2JpsiMuNu.cc  -lstdc++ -lCore -lRIO -lTree -lPhysics -lHammerTools -lHammerBase -lHammerCore -lFormFactors -lAmplitudes -lRates
```

**Comment by yipengsun** [comment]
Note: Zishuo's code compiled with `gcc 9` but `clang 7` complains about reference ambiguity. Removing
```cpp
using namespace Hammer;
```

solved the problem.

**Comment by yipengsun** [comment]
Zishuo uses the following decay descriptor for MC particles:

```python
jpsimudecay = "[B_c+ => ^(J/psi(1S) => ^mu+ ^mu-) ^mu+ ^nu_mu]CC"
MCBc2JpsiMuNuTuple = MCDecayTreeTuple("MCBc2JpsiMuNuTuple")
MCBc2JpsiMuNuTuple.TupleName = "MCBc2JpsiMuNuDecayTree"
MCBc2JpsiMuNuTuple.Decay = jpsimudecay
MCBc2JpsiMuNuTuple.addBranches({
    "Bc" : "[^(B_c+ => (J/psi(1S) => mu+ mu-) mu+ nu_mu)]CC"
    , "Jpsi" : "[B_c+ => ^(J/psi(1S) => mu+ mu-) mu+ nu_mu]CC"
    , "MuP" : "[B_c+ => (J/psi(1S) => ^mu+ mu-) mu+ nu_mu]CC"
    , "MuM" : "[B_c+ => (J/psi(1S) => mu+ ^mu-) mu+ nu_mu]CC"
    , "BachMu" : "[B_c+ => (J/psi(1S) => mu+ mu-) ^mu+ nu_mu]CC"
    , "NuMu" : "[B_c+ => (J/psi(1S) => mu+ mu-) mu+ ^nu_mu]CC"
    })
MCBc2JpsiMuNuTuple.ToolList = [
    "MCTupleToolKinematic"
    , "TupleToolEventInfo"
]
```

```python
MCBc2JpsiTauNuTuple.addBranches({
"Bc" : "[^(B_c+ -> (J/psi(1S) => mu+ mu-) (tau+ => mu+ nu_mu nu_tau~) nu_tau)]CC"
    , "Jpsi" : "[B_c+ -> ^(J/psi(1S) => mu+ mu-) (tau+ => mu+ nu_mu nu_tau~) nu_tau]CC"
    , "MuP" : "[B_c+ -> (J/psi(1S) => ^mu+ mu-) (tau+ => mu+ nu_mu nu_tau~) nu_tau]CC"
    , "MuM" : "[B_c+ -> (J/psi(1S) => mu+ ^mu-) (tau+ => mu+ nu_mu nu_tau~) nu_tau]CC"
    , "Tau" : "[B_c+ -> (J/psi(1S) => mu+ mu-) ^(tau+ => mu+ nu_mu nu_tau~) nu_tau]CC"
    , "BachMu" : "[B_c+ -> (J/psi(1S) => mu+ mu-) (tau+ => ^mu+ nu_mu nu_tau~) nu_tau]CC"
    , "NuMu" : "[B_c+ -> (J/psi(1S) => mu+ mu-) (tau+ => mu+ ^nu_mu nu_tau~) nu_tau]CC"
    , "NuTauBar" : "[B_c+ -> (J/psi(1S) => mu+ mu-) (tau+ => mu+ nu_mu ^nu_tau~) nu_tau]CC"
    , "NuTau" : "[B_c+ -> (J/psi(1S) => mu+ mu-) (tau+ => mu+ nu_mu nu_tau~) ^nu_tau]CC"
})
```

Note that here the arrow is `=>` instead of `->`. The `=>` includes radiative photons.

**Comment by yipengsun** [comment]
From [this HAMMER source code](https://gitlab.com/mpapucci/Hammer/-/blob/master/src/Amplitudes/AmplBDLepNu.cc), I believe we also need momenta from neutrinos.

But Phoebe doesn't seem to be using any of the neutrino info. I guess the old way of doing FF reweighting was not precise enough?

Still, from [arXiv:1606.08030v2](https://arxiv.org/pdf/1606.08030.pdf), I don't see explicit dependencies for momenta of the leptons (neither tau nor nu_tau), so I guess HAMMER improved the FF by adding some helicity angle knowledge?

**Comment by yipengsun** [comment]
Subsequent development will happen in `ff-reweight` branch.

**Comment by yipengsun** [comment]
Now I can reconstruct decay of B -> D Mu Nu with `MCDecayTreeTuple`. The problem now is that most TupleTools for data won't apply here. For example, I lost all Muon PID info for MC.

**Comment by yipengsun** [comment]
I got the following error for B- -> D0 Mu tree:
```
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolAngles', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolL0Calo', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolMCBackgroundInfo', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolMCTruth', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolMuonPid', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolPid', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolTISTOS', check your syntax StatusCode=FAILURE
TupleBminusMCMu     ERROR MCDecayTreeTuple:: Can't get the tool 'TupleToolTrackInfo', check your syntax StatusCode=FAILURE
```

Need to investigate how to add tool to `MCDecayTreeTuple`. This is probably the reason of not having any Muon PID branch.

**Comment by yipengsun** [comment]
`Phys/DecayTreeTuple/src/MCDecayTreeTuple.cpp` does not exist in latest `Analysis`. Perhaps we should not use this after all?

**Comment by yipengsun** [comment]
I didn't understand Zisho's idea until now. The idea is, we still use `DecayTreeTuple` on MC to reconstruct most variables, and use `MCDecayTreeTuple` to provide supplemental true momenta info only.

**Comment by yipengsun** [comment]
The MC DaVinci reconstruction is extremely SLOW.

**Comment by yipengsun** [comment]
Phoebe points out that Muon "true" momentum might not be faithfully reconstructed, due to "FSR" (PHOTOS emission). So it might be prudent to use `P(B)-P(Dst)-P(nu)` for Muon momentum.

**Comment by yipengsun** [comment]
Something's still not right. For the MC, I'm trying to reconstruct auxiliary trees that contain true momenta of tau and neutrinos for **EVENTS that pass nominal selection** defined in the DaVinci script.

From DaVinci log, I see that we have ~4.7k events that passes `B0 -> Dst Tau Nu` selections and reconstruction. Therefore, our auxiliary tree should contain roughly 4.7k events (given that candidates with the same UID are rare). However, I got ~20k candidates in the aux tree.

**Comment by yipengsun** [comment]
Hmm, none of existing examples of `MCDecayTreeTuple` configures the `Input` property of the MC tuple. I guess this means that `MCDecayTreeTuple` will always loop over all events in the `.dst` file?

**Comment by yipengsun** [comment]
I tried to not set the the `Inputs` attribute of the `MCDecayTreeTuple`, and the output doesn't change. So I guess `MCDecayTreeTuple` always runs over every single MC event in the `.dst` files.

**Comment by yipengsun** [comment]
I confirmed that I am using `B -> Dst Tau (-> Mu Nu) Nu` MC sample. The DecFile ID is: `11574010`, and its definition can be found at [cern gitlab](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/master/dkfiles/Bd_Dst+taunu,mununu=TightCuts.dec).

So if there's no internal cuts for `MCDecayTreeTuple`, then we should be able to reconstruct `B -> Dst Tau (-> Mu Nu) Nu` for **EVERY** event in the `.dec` file.

**Comment by yipengsun** [comment]
I'm a bit confused about the Gauss fields of this `.dec` file:
```
# EventType: 11574010
#
# Descriptor: {[[B0]nos => nu_mu mu+ (D*(2010)- => (D~0 -> K+ pi-) pi-)]cc, [[B0]os => anti_nu_mu mu- (D*(2010)+ => (D0 -> K- pi+) pi+)]cc}
#
# NickName: Bd_Dst+taunu,mununu=TightCuts
# Cuts: 'LoKi::GenCutTool/TightCut'
# InsertPythonCode:

#from Configurables import LoKi__GenCutTool
#from Gauss.Configuration import *
#gen = Generation()
#gen.SignalRepeatedHadronization.addTool ( LoKi__GenCutTool , 'TightCut' )
#tightCut = gen.SignalRepeatedHadronization.TightCut
#tightCut.Decay = "[ (Beauty) ==> ^(D~0 -> ^K+ ^pi- {gamma} {gamma} {gamma}) ^mu+ nu_mu {X} {X} {X} {X} {X} {X} {X} {X} ]CC"
```

I don't see any explicit `Tau` here. @Svende could you help me understand what is actually going on here?

The actual decay chains look fine though.

**Comment by yipengsun** [comment]
Here's what's confusing to me:

What we know (supposedly):

1. We are using correct signal MC sample: `B -> Dst Tau (-> Mu Nu) Nu`
2. `MCDecayTreeTuple` runs on every input event, and this is not configurable
3. `MCDecayTreeTuple` doesn't apply any sort of cut

I'm running over 27970 MC signal events. I'm also reconstructing two trees at once:

1. **Normal reco**: Select and reconstruct events with the same criteria as in real data, with `DecayTreeTuple`
2. **Reco with `Tau` and `Nu`**: Get the true momenta and PID of `Tau` and `Nu` (needed for HAMMER), with `MCDecayTreeTuple`

Naively, one would expect:

1. 27970 events in **Reco with `Tau` and `Nu`** tree (we should be able to reconstruct this decay chain for every input event)
2. Smaller number of events in **Normal reco**, and this should be a **subset** of the **Reco with `Tau` and `Nu`**

However, I get the following:
![reco_modes](https://user-images.githubusercontent.com/33738176/95775194-8baf3100-0cf4-11eb-989d-34dfc4b555c7.png)

@ZishuoYang have you encountered something similar?

**Comment by yipengsun** [comment]
Here's some background on how I discovered this:

Initially, I'm just blindly following Zishuo's [`plot_ratio.py`](https://github.com/ZishuoYang/my-hammer-reweighting/blob/master/plot_ratio.py) by adding regular tree to HAMMER weight tree as a friend:
```python
# Add friend to associate events
tTup.BuildIndex("runNumber","eventNumber")
tHam.AddFriend(tTup)
```

But the generated plot only has 140 events in total:
![el](https://user-images.githubusercontent.com/33738176/95775994-0a589e00-0cf6-11eb-96a4-ccaf22199415.png)

Then I did the reverse: adding HAMMER weight tree to regular tree as a friend, but now generated plots are empty.

I did a quick `Scan` with interactive root (adding HAMMER to regular as friend), and discovered that for some events in regular tree, there's no associated FF weight to it!

Then I used [`uidcommon`](https://github.com/umd-lhcb/pyTuplingUtils/blob/master/bin/uidcommon), and found out that there are **only 1600** common events between these two trees.

**Comment by Svende** [comment]
> I'm a bit confused about the Gauss fields of this `.dec` file:
> 
> ```
> # EventType: 11574010
> #
> # Descriptor: {[[B0]nos => nu_mu mu+ (D*(2010)- => (D~0 -> K+ pi-) pi-)]cc, [[B0]os => anti_nu_mu mu- (D*(2010)+ => (D0 -> K- pi+) pi+)]cc}
> #
> # NickName: Bd_Dst+taunu,mununu=TightCuts
> # Cuts: 'LoKi::GenCutTool/TightCut'
> # InsertPythonCode:
> 
> #from Configurables import LoKi__GenCutTool
> #from Gauss.Configuration import *
> #gen = Generation()
> #gen.SignalRepeatedHadronization.addTool ( LoKi__GenCutTool , 'TightCut' )
> #tightCut = gen.SignalRepeatedHadronization.TightCut
> #tightCut.Decay = "[ (Beauty) ==> ^(D~0 -> ^K+ ^pi- {gamma} {gamma} {gamma}) ^mu+ nu_mu {X} {X} {X} {X} {X} {X} {X} {X} ]CC"
> ```
> 
> I don't see any explicit `Tau` here. @Svende could you help me understand what is actually going on here?
> 
> The actual decay chains look fine though.

Hi Yipeng,
concerning this part `tightCut.Decay = "[ (Beauty) ==> ^(D~0 -> ^K+ ^pi- {gamma} {gamma} {gamma}) ^mu+ nu_mu {X} {X} {X} {X} {X} {X} {X} {X} ]CC"`. This is a decay descriptor following the LOKI syntax using arrows as specified here (not trivial at all and very confusing): https://twiki.cern.ch/twiki/bin/view/LHCb/FAQ/LoKiNewDecayFinders#Grammar_in_short. So basically here you select any D~0 (-> K+ pi-) mu+ nu_mu events which come from a beauty mother. Using the arrow ==> the D~0 and mu+ don't have to be direct daughters, it allows for intermediate resonances such as the Dst+ and the tau in this case. Those are just the final state particles that you require.  Also this decay descriptor is used for the tight generator level cuts following line 23 of the dec file. I hope that helps.

**Comment by ZishuoYang** [comment]
> Naively, one would expect:
> 
> 1. 27970 events in **Reco with `Tau` and `Nu`** tree (we should be able to reconstruct this decay chain for every input event)
> 2. Smaller number of events in **Normal reco**, and this should be a **subset** of the **Reco with `Tau` and `Nu`**
> 
> However, I get the following:
> ![reco_modes](https://user-images.githubusercontent.com/33738176/95775194-8baf3100-0cf4-11eb-989d-34dfc4b555c7.png)
> 
> @ZishuoYang have you encountered something similar?

No, I don't think I saw something like that. Each reconstructed event from MC should have its MC truth info. 

You may want to sanity-check the MC truth info in your "normal reco" tree, against the truth info in your MCDecayTree. (I assume you saved some truth info for some reconstructed visible/final states.)

**Comment by yipengsun** [comment]
I did the following tests:

1. In DaVinci, I removed all tupling but the **Reco with `Tau` and `Nu`**, and I get the same number events as before.
2. I tried to comparing MC true PE of B, and I get this:
```
************************************************
*    Row   * b_true_pe * aux.b_tru *      w_ff *
************************************************
*        0 * 84602.539 * 84602.539 * 0.5639012 *
*        1 * 85232.130 * 85232.130 * 2.6594318 *
*        2 * 94993.611 * 94993.611 * 0.3786424 *
*        3 * 138223.74 * 138223.74 * 0.8212659 *
*        4 * 143751.35 * 143751.35 * 1.0356138 *
*        5 * 192888.07 * 192888.07 * 0.8166537 *
*        6 * 114255.07 * 114255.07 * 0.7703216 *
*        7 * 56538.908 *           *           *
*        8 * 260527.48 *           *           *
*        9 * 330234.65 * 330234.65 * 0.6905436 *
*       10 * 165900.21 * 165900.21 * 0.7593134 *
*       11 * 318488.32 *           *           *
*       12 * 111411.08 * 111411.08 * 0.7669847 *
*       13 * 153925.84 *           *           *
*       14 * 116193.47 * 116193.47 * 1.4770265 *
*       15 * 155554.77 *           *           *
*       16 * 225910.11 * 225910.11 * 1.0633131 *
*       17 * 150019.42 *           *           *
*       18 * 209693.45 * 209693.45 * 0.3691686 *
*       19 * 110697.25 *           *           *
*       20 * 105866.33 *           *           *
*       21 * 80090.565 *           *           *
*       22 * 131947.40 * 131947.40 * 0.8056939 *
*       23 * 123506.29 *           *           *
*       24 * 154410.44 *           *           *
```

I think there's some real discrepancies between the two trees, and this is likely due to some unknown mistake on DaVinci step.

@ZishuoYang, can you commit your generated sample root files to your hammer repo, so I can verify that my way of identifying the same event works? (basically verify my `uidcommon` works)?

@ZishuoYang @Svende Here's my decay descriptor for reconstructing the MC tree about `B -> Dst Tau Nu` decay:
```python
'${b0}[B~0 => ${dst}(D*(2010)+ => ${d0}(D0 => ${k}K- ${pi}pi+) ${spi}pi+) ${tau}(tau- => ${mu}mu- ${anu_mu}nu_mu~ ${nu_tau}nu_tau) ${anu_tau}nu_tau~]CC'
```

Does this look correct to you?

I think I'm running out of ideas as of now. I will ask this in Wednesday's meeting, and will ask on DaVinci list if we don't have better ideas.

**Comment by Svende** [comment]
It could be something to do with the truth matching for B~0 and B0. I remember a conversation with Greg a while ago where for truth matching you have to use rather [B0]nos and [B0]os. Can you try using `[[B0]nos => nu_tau tau+ (D*(2010)- => (D~0 -> K+ pi-) pi-)]cc, [[B0]os => anti_nu_tau tau- (D*(2010)+ => (D0 -> K- pi+) pi+)]cc` instead with the corresponding tau decay?

**Comment by yipengsun** [comment]
I tried the following decay descriptor:
```python
'${b0}[[B0]os => ${dst}(D*(2010)+ => ${d0}(D0 -> ${k}K- ${pi}pi+) ${spi}pi+) ${tau}(tau- => ${mu}mu- ${anu_mu}nu_mu~ ${nu_tau}nu_tau) ${anu_tau}nu_tau~]CC'
```

and I got 0 reconstructed B. So I don't think it works. Maybe Greg's suggestion was for MC toolkit? Because I noticed that you are using lower case `cc`, but `DecayTreeTuple` only accept uppercase `CC`.

**Comment by yipengsun** [comment]
Also, `anti_nu_mu` is equivalent to `nu_mu~`. I tried both, and neither gave me any event in the output ntuple.

**Comment by ZishuoYang** [comment]
@yipengsun OK, although I'm not sure if DaVinci log was saved, I'll look into these soon.

**Comment by yipengsun** [comment]
@Svende Actually, your last suggestion works! By changing the decay descriptor to the following:

```python
    '(' +
    '${b0}[B~0 => ${dst}(D*(2010)+ => ${d0}(D0 => ${k}K- ${pi}pi+) ${spi}pi+) ${tau}(tau- => ${mu}mu- ${anu_mu}nu_mu~ ${nu_tau}nu_tau) ${anu_tau}nu_tau~]CC' +
    '||'
    '${b0}[B0 => ${dst}(D*(2010)+ => ${d0}(D0 => ${k}K- ${pi}pi+) ${spi}pi+) ${tau}(tau- => ${mu}mu- ${anu_mu}nu_mu~ ${nu_tau}nu_tau) ${anu_tau}nu_tau~]CC' +
    ')'
```

I was able to reconstruct truth info for all events (27971, with 1 duplicate UID, so really 27970)!

**Comment by yipengsun** [comment]
With the new MC decay descriptor that taken B0 oscillation into account, I got the following error for HAMMER reweighting:
```
Hammer.ProcRequirements: ERROR  An amplitude involving the parent particle is not implemented! 'Oh cock'...in Hungarian!
```

**Comment by yipengsun** [comment]
I guess I have to manually invert the ID of B when it oscillates.

**Comment by yipengsun** [comment]
@manuelfs @Svende I finally generated some reweighted fit variable comparison plots:
![el](https://user-images.githubusercontent.com/33738176/96715658-359d5600-13a4-11eb-8dda-55583639628e.png)
![mm2](https://user-images.githubusercontent.com/33738176/96715660-3635ec80-13a4-11eb-91af-23c4aae3385a.png)
![q2](https://user-images.githubusercontent.com/33738176/96715665-36ce8300-13a4-11eb-95f7-f1b11aa12c4e.png)

Blue is original, Red is reweighted.

Note that for run 1 `B0 -> D* Tau Nu`, we are using ISGW2 parameterization:
```
Decay B0sig 
   1   MyD*-        Mytau+  nu_tau         PHOTOS  ISGW2;
Enddecay
```

I configured the input FF parameterization as `ISGW2` for Hammer:
https://github.com/umd-lhcb/hammer-redist/blob/ab05421923ba90d373317ddac956b3c977b24161/src/rdx-run1-sample.cpp#L124

**Comment by manuelfs** [comment]
Thank you Yipeng. A few questions for you so that you think a bit further.

Is this what you would expect? How would you know what to expect? Would it be easier to validate the reco or the true distributions?

**Comment by yipengsun** [comment]
Below are reweighted vs. true distributions.

![el_true](https://user-images.githubusercontent.com/33738176/97112756-5fc57f80-16e6-11eb-82d0-1a0ed6bdd41f.png)
![mm2_true](https://user-images.githubusercontent.com/33738176/97112757-605e1600-16e6-11eb-94f8-972d74553db6.png)
![q2_true](https://user-images.githubusercontent.com/33738176/97112759-605e1600-16e6-11eb-9f95-783d04e8cef7.png)

@manuelfs can you give me a pointer about your code in generated expected distributions for `q2, mm2, el`?

**Comment by yipengsun** [comment]
Forgot to say, it's still ISGW2 -> BGL, but it's just one parameter away from CLN. Once I have your code, I can easily change mine to reweight to CLN.

**Comment by manuelfs** [comment]
My FF implementations for ISGW2 and CLN can be found at [ff_dtaunu](https://github.com/manuelfs/babar_code/blob/master/src/ff_dtaunu.cpp) and [ff_dstaunu](https://github.com/manuelfs/babar_code/blob/master/src/ff_dstaunu.cpp), and some rate calculations at [ratecalc](https://github.com/manuelfs/babar_code/blob/master/src/ratecalc.cpp).

You can make a q2 plot for the SM and some 2HDM scenarios with `./compile.sh && ./run/plot_q2_2hdm.exe`.

But you don't need to run all of this to see that there is a pretty obvious problem with your q2 distribution which you need to debug. Hope tomorrow you have some ideas.

**Comment by yipengsun** [comment]
I still did a baseline check for reweighting from ISGW2 to ISGW2, and the weights are identically 1, as expected. I think the utility of this test is that the MC are indeed generated with ISGW2.

**Comment by yipengsun** [comment]
Changing the reweight scheme to ISGW2 -> CLN, and the output looks a lot more reasonable:
![el_true](https://user-images.githubusercontent.com/33738176/97121811-54dc1080-1721-11eb-9e50-d6cc0b086bd3.png)
![mm2_true](https://user-images.githubusercontent.com/33738176/97121812-5574a700-1721-11eb-8765-b27d9618ff0d.png)
![q2_true](https://user-images.githubusercontent.com/33738176/97121813-560d3d80-1721-11eb-9e21-65ae6208bc21.png)

**Comment by yipengsun** [comment]
Here's the comparison plot. We have 4 histograms in this plot:

1. Reference CLN q2 distribution, normalized to 1
2. Reference ISGW2 q2 distribution, normalized
3. Original q2 in MC, normalized
4. Reweighted q2 in MC, normalized

There's a complication about normalization:

1. All 4 histograms are rescaled by:
    ```cpp
    histo.Scale(1/histo.Integral("width"))
    ```

2. Still, the histograms are of different heights, making comparison of shapes harder
3. For _Original q2 in MC_, rescale again so that the maximum of it equals to the maximum of _Reference ISGW2_
4. For _Reweighted q2 in MC_, rescale with _Reference CLN_

Here's the final plot
![validate_ff](https://user-images.githubusercontent.com/33738176/98455155-20c70d80-216d-11eb-9121-b4321f9a2a81.png)

My comment is: It's hard to say if the reweighting is successful. But CLN seems to be pushing q2 to higher values, and this is consistent with what we saw in the original vs. reweighted MC.

**Comment by yipengsun** [comment]
On a second thought, I should not scale MC histograms with a bias. So now I scale both such that the maximum of them is the maximum of _Reference ISGW2_. Here's the new plot:
![validate_ff](https://user-images.githubusercontent.com/33738176/98455413-8668c900-2170-11eb-97a3-611954ea26e1.png)

**Comment by yipengsun** [comment]
Or, maybe even better, scale both histograms with the same scaling factor:
![validate_ff](https://user-images.githubusercontent.com/33738176/98469432-cc10aa80-21df-11eb-8e2b-c22042d9c301.png)

**Comment by yipengsun** [comment]
A quick check on the [`.dec` file for run 1 MC](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/master/dkfiles/Bd_Dst+taunu,mununu=TightCuts.dec) confirms my impression that ISGW2 FF parameterization doesn't **seem** have configurable parameters, so I still have no idea why the _Reference ISGW2_ curve is deviating that much from the _q2 original_ histogram.

**Comment by yipengsun** [comment]
I'm glad that I checked again. In the comparison plot, I was using **reconstructed q2**, NOT **true q2**. Here's the latest plot with **true q2**:
![validate_ff](https://user-images.githubusercontent.com/33738176/98488741-21be7480-222b-11eb-8351-ea078d802510.png)

**Comment by yipengsun** [comment]
Here's the same plot, with honest normalization, and I think it's harder to compare shapes:
![validate_ff](https://user-images.githubusercontent.com/33738176/98489221-69de9680-222d-11eb-85bf-499586e6edc7.png)

**Comment by manuelfs** [comment]
Good comparisons. I agree with your assessment: the reweighting is pushing the distribution in the right direction. The shapes of the MC and theory are similar, but not identical. This is expected because you are not saving every generated event, only those in which we are able to reconstruct a D*mu, which would skew the q2 distribution.

Small advice about format. Not crucial, but to make the reader be able to understand the plot quicker it would be better if the two ISGW2 distributions had the same color but different line style, same for CLN. Also, if the legend said "MC q2 ISGW2" instead of "q2 original" one wouldn't need to read the text 6 posts above.
