### ISSUE TITLE
Update documentation for submitting jobs to GRID

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#52]
I need to improve the documentation on how to submit a GRID job. 

Note that currently `ganga` is broken on `lxplus` mysteriously:
```
ERROR    Failed to execute command: /tmp/suny/tmpsvrrp5xi.sh
ERROR    Tried to execute command in: /afs/cern.ch/user/s/suny/build/DaVinciDev_v45r4
ERROR    StdErr: No such file or directory
CMake Error: Generator: execution of make failed. Make command was: /cvmfs/lhcb.cern.ch/lib/bin/Linux-x86_64/ninja ganga-input-sandbox &&
make: *** [ganga-input-sandbox] Error 1

ERROR    StdOut: cmake --build /afs/cern.ch/user/s/suny/build/DaVinciDev_v45r4/build.x86_64-centos7-gcc9-opt --target ganga-input-sandbox --

ERROR    GangaException: Failed to Execute command
ERROR    GangaException: Failed to Execute command ... reverting job 73 to the new status
INFO     job 73 status changed to "new"
ERROR    JobError: Error: GangaException: Failed to Execute command
```

Before I proceed updating the doc, I need to fix this problem.

**Comment by yipengsun** [comment]
`ganga` was trying to make a sandboxed DaVinci for the DIRAC backend, and the actual command that failed is this:
```
cmake --build /afs/cern.ch/user/s/suny/build/DaVinciDev_v45r4/build.x86_64-centos7-gcc9-opt --target ganga-input-sandbox --
```

The error message is:
```
No such file or directory
CMake Error: Generator: execution of make failed. Make command was: /cvmfs/lhcb.cern.ch/lib/bin/Linux-x86_64/ninja ganga-input-sandbox &&
```

These agree with what we saw from `ganga`'s own error output.

**Comment by yipengsun** [comment]
Hmm, this is probably because  incompatible Python versions. I did a quick search on LHCb mailing lists, and found [this](https://groups.cern.ch/group/lhcb-core-soft/Lists/Archive/Flat.aspx?RootFolder=%2fgroup%2flhcb%2dcore%2dsoft%2fLists%2fArchive%2fGanga%20submit%20fails%20cannot%20find%20ninja%20on%20cvmfs&FolderCTID=0x012002002DAD3147837DAE4A9BC6BABCB65AB725).

**Comment by yipengsun** [comment]
Recompiling locally seems to be the solution, at least for [others](https://groups.cern.ch/group/lhcb-distributed-analysis/Lists/Archive/Flat.aspx?RootFolder=%2fgroup%2flhcb%2ddistributed%2danalysis%2fLists%2fArchive%2fGanga%20submit%20fails%20cannot%20find%20ninja%20on%20cvmfs&FolderCTID=0x01200200AD716970E9BBD0488B2362305E8E167D).

**Comment by yipengsun** [comment]
This might be needed in the documentation:
```
export BINARY_TAG=$CMTCONFIG
```

**Comment by yipengsun** [comment]
Recompiling locally does solve the ganga submission issue.

**Comment by yipengsun** [comment]
@afernez Hey Alex, I finally made a draft for submitting jobs to GRID: https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/grid_job
This guide should be mostly self-contained. Feel free to post your suggestions about it here.

**Comment by afernez** [comment]
Thanks Yipeng, I will (probably slowly) look through it and document any comments in this issue.

**Comment by afernez** [comment]
This isn't really a comment about your documentation as much as it is to check I understand your workflow to produce an ntuple. Please correct me if I'm wrong about the general procedure/am missing any important steps needed to produce an ntuple using the scripts in this repo

1. Find the relevant dst files (ie. a list of LFNs) in the bookkeeping (and then, often it's convenient to download the dst files to julian so you can access them without lxplus). For example, for 2015 data, I believe the LFNs have paths something like `/LHCb/Collision15/Beam6500GeV-VeloClosed-MagUp/Real Data/Reco15a/Stripping24r2/90000000/SEMILEPTONIC.DST` (though, I'm not sure if I should be choosing mag up or down, velo closed or open, etc...)
2. Edit a cond file with input dst paths, characteristics (eg. specify the year), output ntuple name, and "monitoring sequences" (eg. 'CUTFLOW')
3. Run a command (on lxplus or in a docker) to have DaVinci process the job with a specified reco and cond file (I assume we re-use the [run 2] [reco_Dst_D0.py script](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py) for all [run 2] productions, making edits as necessary, but I guess at least for now I shouldn't have to edit this script), either following your [directions using a docker](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/step1_davinci/), assuming the file is downloaded to julian, or [your directions for submitting the job to the grid](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/grid_job/), which works whether the dst files are downloaded to julian or they're only available on the grid.
4. Re-submit any failed subjobs
5. Merge ntuples from each subjob
6. Check the ntuple (perhaps just inspecting it in a `TBrowser` as a first step; I'll worry more about this step later)
7. Save the produced, merged ntuple on julian

I'm guessing each ntuple production (done on the grid) will also require editing [ganga_jobs.py](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/scripts/ganga/ganga_jobs.py). For example, for the ntuple I currently want to produce for 2015, should I modify [line 42](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/22582db3a97e1629b1f2cd71b3e6d3584e431967/scripts/ganga/ganga_jobs.py#L42), or more likely just add an entry to the `LFN_PATH` dict `std-2015: /LHCb/Collision15/Beam6500GeV-VeloClosed-Mag{polarity}/Real Data/Reco15a/Stripping24r2/90000000/SEMILEPTONIC.DST`? Beyond this, quickly looking through the script, I think this is the only edit that would have to be made, at least for the 2015 data ntuple production.

**Comment by yipengsun** [comment]
@afernez here are some of my thoughts on test DaVinci script locally with 2015 data and then submit 2015 production to the GRID:

1. Create a new branch called `2015-production`
2. From DIRAC, download 1 or 2 sample `.dst` files
    For info on how to download `.dst` files to `lxplus`, follow [this guide](https://umd-lhcb.github.io/lhcb-ntuples-gen/data/data_management/#download-data-files-with-lxplus)
    After downloading `.dst` files and `.py` files (`.py` files can be downloaded from DIRAC directly; they are of this form: `'LHCb_Collision11_Beam3500GeVVeloClosedMagDown_Real Data_Reco14_Stripping21r1_90000000_SEMILEPTONIC.DST.py'`), create a `data-2015-md` folder in `run2-rdx/data`, and place these files verbatim there
3. `git add <py_file>`, then `git annex add <dst_files>`, then commit.
4. In `run2-rdx/conds`, copy `cond-std-2016.py` as `cond-std-2015.py`, and update the `IOHelper` section to point to the right 2015 `.dst` files; also update `DataType`.
5. Follow [this guide](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/step1_davinci/) to test it locally
6. If DaVinci generates a ntuple successfully, follow the [GRID guide](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/grid_job/) to submit a 2015 job to GRID

**Comment by yipengsun** [comment]
I think you are mostly right. But for point 3: When running DaVinci locally (on your computer) with a docker, you can just download `.dst` files to your computer, test them, then commit `.dst` files with `git annex`, then synchronize them to `julian`.

You are absolutely right about having to change `ganga_jobs.py`. It currently doesn't have LFNs for 2015 listed, so you need to update that.

Feel free to do that in a separate branch (so I can do a double check) once you have time. As Manuel said, we don't need to rush this.

**Comment by yipengsun** [comment]
@afernez Also, for testing `.dst` files locally, you can try following [this](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/step1_davinci/).

Unfortunately setting up `docker` and other stuff can be hard, especially on Windows. Feel free to post questions!

**Comment by afernez** [comment]
I am actually having a confusing issue just adding the dst files. I'm not sure if the problem is specific to WSL2, but when I run `git annex add <dst_file>` I get an error 
`git-annex: ../../../.git/annex/othertmp/00102354_00000124_1.semileptonic.dst.0/00102354_00000124_1.semileptonic.dst: rename: permission denied (Permission denied) failed`
`git-annex: add: 1 failed`

Googling the error, [this](https://git-annex.branchable.com/bugs/WSL1__58___git-annex-add_fails_in_DrvFs_filesystem/) seemed relevant, which at the end in the comments suggests setting the config `annex.addunlocked=true`. Trying this by running `git config annex.unlocked true` (should only set the config in my cloned repo I believe), I am able to `git annex add` the dst file. But, then, the dst file isn't locked. Before I commit anything, do you think it's alright to proceed like this and then lock the file using `git annex lock <dst_file>` after committing?

**Comment by yipengsun** [comment]
Hmm, this is really weird. Can you list the `git-annex version`? Maybe you should try updating `git-annex`.

Also, I see that you are probably doing this in `2015_prodction`. Have you tried to `git annex sync julian`? If so, I can try checking out your branch and see if it works.

**Comment by afernez** [comment]
My `git-annex` seems to be updated already, version `8.20200226`; my local repository version is set to `8`.
I just synced with julian, but I don't think the two test dst files I've copied into my local `data-2015-md` folder will show up because they're untracked until I can successfully add them.

**Comment by yipengsun** [comment]
Hmm, your `git-annex` is the first release that supports local repository of version `8`. Maybe there's some problems with this release so that the next release happened on Mar 09, 2020. [Here](http://source.git-annex.branchable.com/?p=source.git&a=search&h=HEAD&st=commit&s=version+8)'s the change log.

Could you try to get a even more recent version? I'm currently at `8.20200810`.

**Comment by yipengsun** [comment]
Here's the change log for `8.20200309`:
```log
git-annex (8.20200309) upstream; urgency=medium

  * Fix bug that caused unlocked annexed dotfiles to be added to git by the
    smudge filter when annex.dotfiles was not set.
  * Upgrade other repos than the current one by running git-annex upgrade
    inside them, which avoids problems with upgrade code making assumptions
    that the cwd will be inside the repo being upgraded. In particular,
    this fixes a problem where upgrading a v7 repo to v8 caused an ugly
    git error message.
  * Fix upgrade failure when a file has been deleted from the working tree.
  * Fix regression 1 month ago that prevented external special remotes from
    using GETCONFIG to query values like "name".
  * Improve behavior when a directory git-annex is writing to gets
    unmounted. Previously it could in some cases re-create the mount point
    and directory tree, and even write object contents to the wrong disk.
  * Don't ignore --debug when it is followed by -c.
  * whereis: If a remote fails to report on urls where a key
    is located, display a warning, rather than giving up and not displaying
    any information.
  * When external special remotes fail but neglect to provide an error
    message, say what request failed, which is better than displaying an
    empty error message to the user.
  * git-annex config: Only allow configs be set that are ones git-annex
    actually supports reading from repo-global config, to avoid confusion.
  * Avoid converting .git file in a worktree or submodule to a symlink
    when the repository is not a git-annex repository.
  * Linux standalone: Use md5sum to shorten paths in .cache/git-annex/locales
  * Fix build with ghc 8.8 (MonadFail)
    Thanks, Peter Simons
  * stack.yaml: Updated to lts-14.27.

 -- Joey Hess <id@joeyh.name>  Mon, 09 Mar 2020 17:04:08 -0400
```

**Comment by yipengsun** [comment]
If a newer version is not available, try remove your current version and use the [linux standalone tarball](https://git-annex.branchable.com/install/Linux_standalone/).

**Comment by yipengsun** [comment]
I think you can submit job to the GRID in the meantime. I checked the `ganga_jobs.py`, and it looks OK to me.

BTW, can you add your `std-2015` line to `ganga_sample_jobs_parser.py` as well? The reason is: Originally, the GRID job name uses **untruncated LFN path**, and that was too long. I had to truncate the LFN, but when you download the ntuples to your localhost, we'd like to go back to the untruncated name. Now you just _submit_ the same job with `ganga_sample_jobs_parser.py`, and it'll output a filename with untruncated LFN.

**Comment by yipengsun** [comment]
@afernez @manuelfs I've added some error checking functionality for ganga job outputs. Please refer to [this doc](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/grid_job/) for all the details.

**Comment by yipengsun** [comment]
So I guess we can consider this done. We should open a separate issue for large productions on the GRID.
