### ISSUE TITLE
Check that run 1 and run 2 RDX DaVinci scripts are essentially the same

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#54]
I'd like to bring a fresh set of eyes to check my run 1 and run 2 RDX DaVinci scripts to make sure: They are the same except for various cuts. The cuts are different because the run 1 and run 2 stripping lines are different.

- Run 1 DaVinci script is [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/9a0b464eb021a3b3af3d7d8570a0459c46d4a7b1/run1-rdx/reco_Dst_D0.py)
- Run 2 is [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/a27875be4fc2ae5b1e729e4ea5a5d1b0081df6fb/run2-rdx/reco_Dst_D0.py)

It would be also helpful if you can confirm that our cuts are the same for the official stripping line cuts. Both Manuel and me has checked for run 1 and run 2; for run 1, we also used some anchor ntuple/comparison method to make sure they agree. Still, I'd like to receive confirmations from more of us.

- [Run 1 stripping](http://lhcbdoc.web.cern.ch/lhcbdoc/stripping/config/stripping21/semileptonic/strippingb2d0muxb2dmunufortaumuline.html)
- [Run 2 stripping](http://lhcbdoc.web.cern.ch/lhcbdoc/stripping/config/stripping28r2/semileptonic/strippingb2d0muxb2dmufortaumuline.html)

@afernez @Svende

**Comment by yipengsun** [comment]
Silly me, I forgot to port the reconstruction for Non-Mu misID samples in the Fake line to run 2. I've ported the change and updated the link in the top post. Sorry!

**Comment by Svende** [comment]
Hi @yipengsun @afernez 
I have checked the Run1 scripts and I have several questions/comments, apologies if I am missing anything:
-  https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L398: Why do you apply here in addition TRCHI2DOF < 3.0 for simulation in addition?
- https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L483: Are the Dst selection cuts documented somewhere?
- https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L533 I didn't get the Dst_ws_Mu part as I don't see that you add the ws muon here
- https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L582 The 'FULL_REFIT' should be explained as well

For the Run2 script I have the following questions:
- https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py#L106 it seems the definitions of the flags are different for run2, is that wanted?
- https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py#L203 here you use different muons wrt Run1 `sel_unstripped_tis_filtered_Mu` but from the comment this is intended
- https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py#L678 can you explain why you don't use the `trigger_list_B` for Run2 whereas you use it in Run1? I don't understand your comment there

Hope that helps!

**Comment by yipengsun** [comment]
>  https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L398: Why do you apply here in addition TRCHI2DOF < 3.0 for simulation in addition?

Don't know why. This cut is inherited blindly from [Phoebe's](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/master/DaVinciReco/YCandReco3.py#L98).

> https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L483: Are the Dst selection cuts documented somewhere?

[These](https://github.com/umd-lhcb/RDRDstRun1AnalysisPreservation/blob/master/DaVinciReco/YCandReco3.py#L121) were chosen by Phoebe

> https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L533 I didn't get the Dst_ws_Mu part as I don't see that you add the ws muon here

Here the input to the `sel_Dst_ws_Mu` contains `sel_D0_ws_combo`, which are D0 filtered from B- wrong sign combo.

Other than that, the decay descriptor is completely normal, because the D* part decays "correctly".

> https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run1-rdx/reco_Dst_D0.py#L582 The 'FULL_REFIT' should be explained as well
 
> For the Run2 script I have the following questions:
> 
> https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py#L106 it seems the definitions of the flags are different for run2, is that wanted?

Yes. For `DV_STRIP`, we want to redo stripping line in DaVinci. For run 2, in addition to these cuts, there's a HLT2 trigger line baked in. So we want to apply that.

> https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py#L203 here you use different muons wrt Run1 `sel_unstripped_tis_filtered_Mu` but from the comment this is intended

Yes. I think the idea is Manuel once said we can always apply HLT TIS filtering later, while preserving this may give us more info for comparison study. I think unless the size of the generated ntuples get too large, we could keep them.
@manuelfs Do you still agree with me that we don't want to apply HLT TIS in DaVinci as all it does is save some diskspace?

> https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/run2-rdx/reco_Dst_D0.py#L678 can you explain why you don't use the `trigger_list_B` for Run2 whereas you use it in Run1? I don't understand your comment there

I think the `TupleToolTISTOS` is a event TupleTool (e.g. The added branches will be `TisTos` instead of `B0_TisTos`), so it's actually pointless/illegal to add this TupleTool to a branch.

**Comment by Svende** [comment]
thanks for your explanations!

**Comment by yipengsun** [comment]
So, do we consider this validated now? If so, you can close this issue.
