### ISSUE TITLE
Apply HLT2 trigger cuts in DaVinci script

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#66]
We just discovered that [the cuts in MC filtering scripts](https://gitlab.cern.ch/lhcb-datapkg/WG/SemilepConfig/-/blob/master/options/Filter_D0TauNu_Muonic.py) is looser than the cuts in `Hlt2XcMuXForTauB2XcMu` line.

We should then find all non-PID cuts inside that HLT2 line and apply these cuts for both FullSim and tracker-only. Note that [Lucia & Co.'s script](https://gitlab.cern.ch/lhcb-slb/B02DplusTauNu/-/blob/master/tuple_production/B2Dmu_AllSpecies_MC2016.py) already has these cuts.

**Comment by yipengsun** [comment]
The `Hlt2XcMuForTauB2XcMu` cuts are documented at umd-lhcb/rdx-run2-analysis#18.

**Comment by yipengsun** [comment]
@Svende I've added the missing cuts in our run 2 reconstruction script. Could you click on the commit message above and see if you agree with my changes?

**Comment by Svende** [comment]
@yipengsun I think you forgot to add a bunch of cuts: K,pi PT for example. I would suggest that you take a look at the corresponding RD+ cuts written here: https://gitlab.cern.ch/lhcb-slb/B02DplusTauNu/-/blob/master/tuple_production/B2Dmu_AllSpecies_MC2016.py#L57 until line 104. You can see that they apply cuts based on a combination of the stripping & HLT2 cuts, whoever is tightest. I think that makes sense as we want to compare our tracker-only MC with FullSim where for the latter the filtering script(https://gitlab.cern.ch/lhcb-datapkg/WG/SemilepConfig/-/blob/master/options/Filter_D0TauNu_Muonic.py) is already applied. Do you have a part in your code where you apply the filtering cuts in case we have tracker-only MC?

**Comment by yipengsun** [comment]
I did looked at their script, I also tried to use the tighter cut among the two. Perhaps I misread a couple of cuts, but I think I did add the missing PT cuts here:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/9e34a3607dfa7ee8cefb3e39423f56f111367b9b/run2-rdx/reco_Dst_D0.py#L277-L283

**Comment by yipengsun** [comment]
And the PT cuts are already at 300 MeV, which is tighter than the Hlt2 cuts (200 MeV):
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/9e34a3607dfa7ee8cefb3e39423f56f111367b9b/run2-rdx/reco_Dst_D0.py#L221-L228

**Comment by Svende** [comment]
ah okay I see, you asked me to check only this part so I did ;) After checking all your code I agree with you

**Comment by yipengsun** [comment]
Great! I'll document the HLT2 cuts in the `rdx-run2-analysis` repo and consider this done.
