### ISSUE TITLE
More ganga improvements

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#68]
Currently we have to manually figure out the name of the output ntuple file from GRID. 

Looking at the source of [`Job` class in `ganga`](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/GPIDev/Lib/Job/Job.py), it seems that we can ~~_abuse_ the `metadata`~~ use the `comment` field to store the final ntuple name on submission with its job.

**Comment by yipengsun** [comment]
Some performance metric:
```
./batch_hadd.sh ~/eos/stash  6201.34s user 84.35s system 76% cpu 2:16:22.06 total
```

**Comment by yipengsun** [comment]
@afernez I've made some improvements to the ganga submitter and the merge script generator so that now the final ntuple filename (the super long one) are used directly, and there's no need to submit the same job locally to get the "correct" filename then rename manually.

Please make sure that you update the ganga submitter, the `~/.ganga.py`, and remake DaVinci on lxplus because we added a bunch of stuff to it.

For more info, please refer to the updated doc [here](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/grid_job/).

Once you think everything is clear, you can close this issue. Otherwise feel free to ask questions directly here.

**Comment by afernez** [comment]
This all seems clear to me. Thanks for documenting what needs to be done. I’ll close the issue, and if questions come up in the future for whatever reason, I’ll reopen the issue and ask here.
