### ISSUE TITLE
Filtering on triggers for run 2 RDX

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#70]
Currently, the unfiltered 2016 MagDown reconstructed ntuples have a size of 127 GB. This is too large for transportation.

I'd like to reuse Phoebe's trigger filtering technique to only keep events that pass our trigger selections. For now I plan to filter on L0 and HLT1 with the following selections:

```python
(b0_L0Global_TIS | d0_L0HadronDecision_TOS) & (d0_Hlt1TrackMVADecision_TOS | d0_Hlt1TwoTrackMVADecision_TOS)
```

**Comment by manuelfs** [comment]
Sounds good. We should think whether any additional cuts can safely be applied to these ntuples

**Comment by yipengsun** [comment]
I think we should first discuss #69 to agree on what cuts should we inherit from run 1 analysis, then try to put these cuts in DaVinci scripts, as we expect the generated ntuples to be huge in general.

**Comment by yipengsun** [comment]
This turns out to be a bad idea: To filtering on D0 and B triggers, it is necessary to have something like this:

```python
def trigger_filter(sel, B_meson='B0', suffix=''):
    sel_name = 'My{}{}Triggered'.format(B_meson, suffix)

    return Selection(
        sel_name,
        Algorithm=FilterDesktop(
            'MyTriggerFilteredB',
            Code='''
INTREE((ABSID == 'D0') & (
    TOS('Hlt1TrackMVADecision', 'Hlt1TriggerTisTos') |
    TOS('Hlt1TwoTrackMVADecision', 'Hlt1TriggerTisTos')
)) & (
    INTREE((ABSID == '{b}') &
        TIS('L0.*', 'L0TriggerTisTos')
    ) |
    INTREE((ABSID == 'D0')) &
        TOS('L0HadronDecision', 'L0TriggerTisTos')
) & (
    INTREE((ABSID == '{b}') &
        TOS('{hlt2}', 'Hlt2TriggerTisTos')
    )
)'''.format(b=B_meson, hlt2=line_hlt)
        ),
        RequiredSelections=[sel]
    )
```

The problem is that we require `INTREE(ABSID == 'D0')` and so on. This might have complicated implications on PID.

I've tried the code above, and compared the output ntuples w/ old ntuples with trigger cuts applied offline. They don't agree in terms of event number. 

For now, I'll use the original method without any trigger filtering. But the code snippet is left here in case anyone in the future want to re-work on this but has better understanding on the PID implications.

**Comment by yipengsun** [comment]
But this is such a desirable feature. At least I should put the code in a separate branch, and start asking DaVinci mailing list.

**Comment by yipengsun** [comment]
This is the relevant code that implemented trigger filtering in DV:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/4aee7b1c94860698a9b531d006d075efb65c8509/run2-rdx/reco_Dst_D0.py#L378-L405

I'll ask someone to check it once we finish preparing our MC request.

**Comment by yipengsun** [comment]
I've checked locally: 

1. Generate `ref.root` w/o any trigger filtering in DaVinci, then apply trigger cuts offline. The resulting ntuple is `ref_cut.root`
2. Generate `comp.root` w/ trigger filtering in DaVinci
3. I compared event UIDs for all trees in these two ntuples. They all agree.

**Comment by yipengsun** [comment]
The trigger filtering results in a 30% size reduction for our real data ntuple. We all agree to apply this trigger filtering in DaVinci.
