### ISSUE TITLE
Inputs for estimating final RDX MC request numbers

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#71]
Here I'll list all inputs to that estimation (WIP):

- Svende's MC ISO study: [`sel_eff_run2_mc.csv`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/archive/21_05_04/scripts/comparison-RDX_selection_efficiency/sel_eff_run2_mc.csv)
- Yipeng's ISO tight study: [`sel_eff_run2_iso_tight.csv`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/archive/21_05_08/scripts/comparison-RDX_selection_efficiency/sel_eff_iso_tight.csv)
    - 2011 MD data: Lumi: 596.061 /pb; Number of events: 56,787,251
    - 2016 MD data: Lumi: 841.275 /pb; Number of events: 490,996,260
    - 2012 MD MC: ID: `11574020` (`B0Dst+MuNu`); BKK: (`Pythia8, Sim08e`) 614577
    - 2016 MD MC: ID: `11574021`; BKK: (`Pythia8, Sim09j`): 1500395

## Note

- For ISO tight study, the following additional cut is applied:
    ```python
    df_q2_sel = df_iso_sel.Filter('FitVar_q2 / 1e6 < 2.85')
    ```
- The ISO tight is generated w/ [this Python script](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/23309c05b85011ef2d4cc5e8ee680be1d6c1831e/scripts/comparison-RDX_selection_efficiency/selection_efficiency.py) and [this shell helper](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/23309c05b85011ef2d4cc5e8ee680be1d6c1831e/scripts/comparison-RDX_selection_efficiency/selection_efficiency_run1_vs_run2_data_mc.sh)
- The offline cuts are defined in [`cut.h`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/37c0edcfedcf9e3729f4e16e12a4cf24d5baf847/include/functor/rdx/cut.h).

**Comment by yipengsun** [comment]
@manuelfs I've listed ISO tight cutflow study CSV and BKK numbers for MC samples in the top post.

**Comment by manuelfs** [comment]
Do the data files correspond to the full 2011 and 2016 MD datasets? 

Also, how come `0.9.4-trigger_emulation/Dst_D0-std/Dst_D0--21_04_27--std--LHCb_Collision16_Beam6500GeV-VeloClosed-MagDown_Real_Data_Reco16_Stripping28r1_90000000_SEMILEPTONIC.DST.root` has 3,358,978 entries while `pre-0.9.0/Dst-cutflow_data/Dst--20_04_03--cutflow_data--data--2016--md.root` has 4,788,649 in the `B0` tree? I guess there's additional cuts now?

The MC cutflow seem to contradict our earlier findings of being more efficient in 2016. Perhaps you're not applying trigger cuts? Can you write out a string with the full cuts applied to `ISOtight`? It just takes too long to parse your script to find what you're applying to the MC.

**Comment by yipengsun** [comment]
> Do the data files correspond to the full 2011 and 2016 MD datasets?

Yes

> Also, how come `0.9.4-trigger_emulation/Dst_D0-std/Dst_D0--21_04_27--std--LHCb_Collision16_Beam6500GeV-VeloClosed-MagDown_Real_Data_Reco16_Stripping28r1_90000000_SEMILEPTONIC.DST.root` has 3,358,978 entries while `pre-0.9.0/Dst-cutflow_data/Dst--20_04_03--cutflow_data--data--2016--md.root` has 4,788,649 in the `B0` tree? I guess there's additional cuts now?

Yes. The trigger cuts are directly applied in the lxplus ntuple concatenation procedure to save some space.

> The MC cutflow seem to contradict our earlier findings of being more efficient in 2016. Perhaps you're not applying trigger cuts? Can you write out a string with the full cuts applied to `ISOtight`? It just takes too long to parse your script to find what you're applying to the MC.

Everything is applied.

The cuts are (for B0):

Trigger:
```
b0_L0Global_TIS || d0_L0HadronDecision_TOS'
d0_Hlt1TrackMVALooseDecision_TOS || d0_Hlt1TwoTrackMVADecision_TOS
b0_Hlt2XcMuXForTauB2XcMuDecision_TOS
```

D0:
```cpp
  if (flag_d0_pid_ok &&
      /* K, pi */
      ((k_hlt1_tos && k_pt > 1.7) || (pi_hlt1_tos && pi_pt > 1.7)) &&
      k_pt > 0.8 && pi_pt > 0.8 && k_pt+pi_pt > 1.4 &&  /* AddB.C, LN2554 */
      //(k_hlt1_tos || pi_hlt1_tos) &&  /* AddB.C, LN2572, this is redundant */
      ////
      k_p > 2 && pi_p > 2 &&
      k_ip_chi2 > 45 && pi_ip_chi2 > 45 &&
      k_gh_prob < 0.5 && pi_gh_prob < 0.5 &&
      /* D0 */
      d0_pt > 2 &&
      d0_hlt2 &&
      d0_endvtx_chi2/d0_endvtx_ndof < 4 &&
      TMath::Log(d0_ip) > -3.5 &&
      d0_ip_chi2 > 9 &&
      d0_dira > 0.9998 &&
      d0_fd_chi2 > 250 &&
      TMath::Abs(d0_m - d0_m_ref) < 23.4  /* This is in MeV!!! */
      )
    // clang-format on
    return true;
  return false;
```

Mu:
```cpp
  if (/* If tracks are well-separated angularly */
      flag_good_trks &&
      /* Mu PID related */
      flag_mu_pid_ok &&
      /* Momentum */
      mu_p > 3 && mu_p < 100 &&
      /* Acceptance */
      mu_eta > 1.7 && mu_eta < 5. &&
      /* Track quality */
      mu_ip_chi2 > 45 && mu_gh_prob < 0.5
      )
    // clang-format on
    return true;
  return false;
```

DstMu combo:
```cpp
  if (/* Daughter particles */
      flag_sel_d0 && flag_sel_mu &&
      /* FD */
      b_fd_trans < 7 &&
      /* Vertex quality */
      b_endvtx_chi2/b_endvtx_ndof < 6 && b_dira > 0.9995 &&
      /* Mass */
      b_m < 5200 &&
      /* Replace Muon mass hypothesis */
      TMath::Abs(d0_m_pi_m - d0_m) > d0_m_diff
      )
    // clang-format on
    return true;
  return false;
```

**Comment by yipengsun** [comment]
Luminosity updated in the top post.

**Comment by yipengsun** [comment]
MC cocktail cutflow bare ntuples are stored in:
```
ntuples/0.9.4-trigger_emulation/Dst_D0-cutflow_mc
```

DstTauNu FullSim MC ntuples are stored in:
```
ntuples/0.9.4-trigger_emulation/Dst_D0-mc
```

**Comment by yipengsun** [comment]
@manuelfs I've updated run 1 signal MC sample sizes in this file:
https://github.com/umd-lhcb/rdx-run2-analysis/blob/master/docs/mc_stats.md

Indeed, there's NO Sim08e sample at all.

Here's some info I used to generate that table:
```
❯ ./size_mc_samples.py -i 11574010 -m year --debug
Before proceed, don't forget to run lhcb-proxy-init!!
Use LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagUp-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagDown-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
For MC ID 11574010
  2012: 1368500

❯ ./size_mc_samples.py -i 11574010 -m year --debug -b NoRICH Pythia8
Before proceed, don't forget to run lhcb-proxy-init!!
Use LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Skip LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Pythia8
Skip LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Pythia8
Skip LFN: /MC/2012/Beam4000GeV-2012-MagUp-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: NoRICH
Skip LFN: /MC/2012/Beam4000GeV-2012-MagDown-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: NoRICH
For MC ID 11574010
  2012: 379549

❯ ./size_mc_samples.py -i 11574010 -m year --debug -b NoRICH Pythia6
Before proceed, don't forget to run lhcb-proxy-init!!
Skip LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Pythia6
Skip LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Pythia6
Use LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Skip LFN: /MC/2012/Beam4000GeV-2012-MagUp-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: NoRICH
Skip LFN: /MC/2012/Beam4000GeV-2012-MagDown-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: NoRICH
For MC ID 11574010
  2012: 360133

❯ ./size_mc_samples.py -i 11574010 -m year --debug -b Sim08
Before proceed, don't forget to run lhcb-proxy-init!!
Skip LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Sim08
Skip LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia6/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Sim08
Skip LFN: /MC/2012/Beam4000GeV-2012-MagDown-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Sim08
Skip LFN: /MC/2012/Beam4000GeV-2012-MagUp-Nu2.5-Pythia8/Sim08a/Digi13/Trig0x409f0045/Reco14a/Stripping20Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST due to blocked keyword: Sim08
Use LFN: /MC/2012/Beam4000GeV-2012-MagUp-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
Use LFN: /MC/2012/Beam4000GeV-2012-MagDown-NoRICHesSim-Nu2.5-Pythia8/Sim09a/Trig0x409f0045-NoRichPIDLines/Reco14c/Stripping21Filtered/11574010/DSTTAUNU.SAFESTRIPTRIG.DST
For MC ID 11574010
  2012: 628818
```

@Svende Sorry for not doing this as the first step!

**Comment by Svende** [comment]
thanks for checking, so what's your conclusion from that? We have all the Sim08a samples already, so they should include all the stats for the FullSim already and we need no more MC staged?
Can you please also check that for the other signal event types we are interested in: 12573021 & 12573000?

**Comment by yipengsun** [comment]
Updated in the same table. The situation is even crazier than I thought.

**Comment by yipengsun** [comment]
BTW, the BKK numbers can be extracted like this:
```
./size_mc_samples.py -i 11574010 -m detail
```

**Comment by Svende** [comment]
@yipengsun You didn't answer my question, so again: so what's your conclusion from that? We have all the Sim08a samples already, so they should include all the stats for the FullSim already and we need no more MC staged?
Philipe is waiting for my answer, so we need to clarify ASAP. What do you think @manuelfs ?

**Comment by yipengsun** [comment]
I updated the table again, and listed the ANA numbers. The answer is: We don't have Sim08e in the first place. Please take another look at that table for more info.

**Comment by yipengsun** [comment]
And currently available dst files are basically agree w/ what is written in the ANA note, so we don't have any file archived in the first place.

**Comment by manuelfs** [comment]
Hi Yipeng,

I'm still a bit confused. If all the Sim08a is staged, looking at your table it seems we should have 360k of D*-τν, and 128k of D0τν available in Pythia8 and similar amounts in Pythia6, is that right? Or are the numbers in your table not what is available?

By the way, is the "total" column the sum of the "ANA" columns?



On May 24, 2021, at 4:23 PM, Yipeng Sun ***@***.******@***.***>> wrote:



And currently available dst files are basically agree w/ what is written in the ANA note, so we don't have any file archived in the first place.

**Comment by yipengsun** [comment]
360k of D*-τν for both polarities. So ~180k for MagDown. I just checked the MagDown total size:

- From merged DaVinci log: 146177
- From DIRAC: 146177

**Comment by yipengsun** [comment]
You can check the DIRAC number with:
```
size_mc_samples.py -i 11574010 -m detail -b MagUp
```

**Comment by manuelfs** [comment]
So we have hundreds of thousands of each signal mode? Didn't you say that there were only 30k or so available?

**Comment by yipengsun** [comment]
34950 candidates in the `TupleB0/DecayTree`, this is after reconstruction.

**Comment by yipengsun** [comment]
For run 2, the same signal decay mode (ID is 11574011 now), there are 152344 candidates in the `TupleB0/DecayTree`.

**Comment by manuelfs** [comment]
That was not clear. So everything is staged and available?

**Comment by yipengsun** [comment]
Yes. The numbers on DIRAC is roughly equal to that listed in the ANA.

**Comment by manuelfs** [comment]
Ok, so we don't need anything from Philippe, right? If so, we should let him know and apologize for our mistake. We can discuss it tomorrow.

**Comment by yipengsun** [comment]
Yes. We don't need him to do anything. We can discuss that and probably I should send an apology.

**Comment by yipengsun** [comment]
@manuelfs Could you commit your code for latest old bare cutflows? I'll do some cleanups and close this issue as the talk has been given.

**Comment by manuelfs** [comment]
I committed the various scripts used for today's MC request talk at the SL WG
- **Old `BARE` cutflow**: I made some destructive surgery on various scripts so I committed this code standalone to the `archive` https://github.com/umd-lhcb/lhcb-ntuples-gen/tree/46ed8bc14688970afcc571f86acb665c274ca6ca/archive/21_05_26/cutflow_oldbare
- **MC/data plots and tables** at https://github.com/umd-lhcb/plot_scripts/blob/f9a6c15aa2e87ca0540df1935992bb82d6f47126/src/rdx/cutflow_data2.cxx and https://github.com/umd-lhcb/plot_scripts/blob/f9a6c15aa2e87ca0540df1935992bb82d6f47126/src/rdx/cutflow_mc.cxx
- **RD(*) ellipses with LHCb projections** at https://github.com/umd-lhcb/plot_scripts/blob/f9a6c15aa2e87ca0540df1935992bb82d6f47126/src/rdx/plot_ellipses_lhcb.cxx
- **Script to read `Neff` from Phoebe's templates and compare them to fitted data yields** at https://github.com/umd-lhcb/mc_tools/blob/d939823d4515015bca6b4bdde3141df64fbfae42/bin/yields_Run1_MC_templates.C

**Comment by yipengsun** [comment]
I did some reformatting for your code, and made sure that the code still runs.

I also renamed the older archive subfolders to give them a more meaningful name.
