### ISSUE TITLE
Track χ²/DOF and data tags

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#72]
In 2016 MD data, we see that the χ²/DOF is not picked around 1. We'd like to know more about it from the tracking experts

## 2016 Data

> Generally, the `CondDB` and `DDDB` tags are different for each dataset you want to use, but will be the same for all DSTs within a given dataset.
> 
> For real collision data, you shouldn’t specify these tags, as the default tags are the latest and greatest, so just remove those lines from the options file.

So, for real data, our initial config is just:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/cc5939c71a094cac4d93687309e9ee0830f679fa/run2-rdx/conds/cond-std-2016.py#L3-L4

Inspecting the DaVinci log, we found out the tags used by DaVinci:
```
# WARNING: Using default tag dddb-20200424-3 for partition DDDB
# WARNING: Using default tag cond-20191004-1 for partition LHCBCOND
# WARNING: Using default tag <latest:2016> for partition DQFLAGS

ToolSvc.GitDDDB      INFO using commit 'dddb-20200424-3' corresponding to 312e726f6f6219889ea38625383668e29d176237
ToolSvc.GitLHCB...   INFO using commit 'cond-20191004-1' corresponding to 79eeebe32d8a0bcde585fdc3f10f23b04762ba4d
ToolSvc.GitONLINE    INFO using commit 'HEAD' corresponding to e101018f0ee44eaa40ef460b0b32cd2b96bb449a
ToolSvc.GitDQFLAGS   INFO using commit 'dq-20170627' corresponding to 81338f7710ec781d087e03868d716433260468e1
```

Now, Svende found [a twiki](https://twiki.cern.ch/twiki/bin/view/LHCb/RecommendedTags) that we should add the following code, so I added them locally:
```python
CondDB( Tags = {"LHCBCOND":"<latest:2016>",
                "DDDB":"<latest:2016>",
                "DQFLAGS":"<latest:2016>"} )
```

Inspecting the DaVinci log again, we found:
```
ToolSvc.GitDDDB      INFO using commit 'dddb-20210215-6' corresponding to 9ea71cba6c18c1d4c65e3bd12d5d5420ad66c718
ToolSvc.GitLHCB...   INFO using commit 'cond-20191004-1' corresponding to 79eeebe32d8a0bcde585fdc3f10f23b04762ba4d
ToolSvc.GitONLINE    INFO using commit 'HEAD' corresponding to e101018f0ee44eaa40ef460b0b32cd2b96bb449a
ToolSvc.GitDQFLAGS   INFO using commit 'dq-20170627' corresponding to 81338f7710ec781d087e03868d716433260468e1
```

A quick plot of `k_TRACK_CHI2NDOF` from these 2 ntuples shows that they are fully on top of each other:
![k_TRACK_CHI2NDOF](https://user-images.githubusercontent.com/33738176/119170429-84f35400-ba63-11eb-90f3-cfbab2eca5a7.png)

## MC

For MC, we should specify the tags.

For run 2 cocktail, the tags are the following:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/cc5939c71a094cac4d93687309e9ee0830f679fa/run2-rdx/conds/cond-cutflow_mc-2016-sim09b.py#L14-L15

For run 2 small MC request:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/cc5939c71a094cac4d93687309e9ee0830f679fa/run2-rdx/conds/cond-mc-2016-sim09j.py#L12-L13

**Comment by Svende** [comment]
In the plots we use our small MC request, AFAIK. So the sim09j ones should be the ones to send via email 
<img width="845" alt="trackchi2ndof_K_pi" src="https://user-images.githubusercontent.com/12730516/119180928-efde6400-ba3e-11eb-93a7-7202923c7837.png">
