### ISSUE TITLE
General improvements on documentation

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#75]
Time to write some documents:

- [x] `nix` procedure and possible warnings
- [x] Development procedure for step-2 ntuples.
- [ ] Add a short intro to `nix`

**Comment by yipengsun** [comment]
@manuelfs @Svende @afernez 

I've updated some Nix-related instruction [here](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/installation/#install-nix).

We can also try to document step-2 process related info at [`docs/ntupling/step2_babymaker.md`](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/docs/ntupling/step2_babymaker.md).

**Comment by yipengsun** [comment]
@manuelfs Do you consider this done for now? Or do you have more planned improvements in the near term?

**Comment by manuelfs** [comment]
I hope to add a `nix` page soon-ish

**Comment by manuelfs** [comment]
Added a bit of `nix` documentation and how to compile `ROOT` in mac to the wiki
https://umd-lhcb.github.io/lhcb-ntuples-gen/software_manuals/nix/
https://umd-lhcb.github.io/lhcb-ntuples-gen/software_manuals/root/
