### ISSUE TITLE
Compare Run1 vs Run2 (FullSim) MC Templates

### ISSUE THREAD

**Issue by afernez** [umd-lhcb/lhcb-ntuples-gen#91]
@yipengsun @manuelfs @Svende Using our newest run2 fullsim MC production ( #87 and #90), we want to compare templates with Phoebe's run1 MC for each control sample as part of an investigation into the differences between the run1 and run2 data control samples (see also #88 and [this presentation](https://github.com/umd-lhcb/group-talks/blob/0cd86358fc805bd9cba50f74d3998d8efc47ce5b/rdx/21-09-16_alex_run12_data_controlsamples_comparison.pdf)).

For now, because it'll probably take some time for me to put these MC template comparison plots into a presentation, here's a [folder](https://github.com/afernez/presentations/tree/5ba107daa96066399e776cf66f395574c531dabc/rdx/run1_run2_mc_ctrlsmp_comp/04-11-21_run12_mc_ctrlsmp) with all the plots inside. And a few notes:

- The run2 ntuples come from [here](https://github.com/umd-lhcb/rdx-run2-analysis/tree/27a1a8488a6c26316db4e30052c64b944cccb577/ntuples/0.9.5-bugfix/Dst_D0-mc)
- The run1 ntuples come from [here](https://github.com/umd-lhcb/rdx-run2-analysis/tree/27a1a8488a6c26316db4e30052c64b944cccb577/fit/src/proctuples)
- For the run2 plots, I've combined together MC decay modes as needed to mimic Phoebe's templates defined in her `redoHistos` scripts
- When filling the run2 plots, I applied the control sample cuts as well as the weights by filling like `template.Fill(mm2, wiso)`, etc
    - I can upload my plotting script, if anyone is interested (it isn't very pretty, though)
- I haven't looked through the plots much yet, but there are some plots that stick out where something seems very different between the two runs. There are also some plots that have something obviously wrong (like run2 plot missing). I haven't thought much about this yet, I just wanted to send out the plots as soon as I could

**Comment by afernez** [comment]
For comparison, [here](https://github.com/afernez/presentations/tree/8ac608a1ee7be3a84bc2ded1c5ebea6ff1e1c880/rdx/run1_run2_mc_ctrlsmp_comp/04-11-21_run12_mc_ctrlsmp_no_run2_weights) are what the plots look like without any weights applied for run2 (so I fill the run2 templates like `template.Fill(mm2, wiso_skim)`)

**Comment by yipengsun** [comment]
Possibly related issues: #86 #89 #90.

I think in today's meeting, We should discuss the validations that I've done, and close these old issues and put updates in this issue only.

**Comment by yipengsun** [comment]
Do we consider this done? Because for now we don't see obvious errors in MC weights, and we can't tell much more until we implement most of the reweighting procedure, and I think that comparison deserves its own issue.

**Comment by manuelfs** [comment]
Phoebe mentioned that the large different in the `DD` template is probably because the muonic BFs of the `D` and `Ds` were wrong in that .dec file, and they had to reweight those. We will have to do that too, but in a different issue
